In [1]:
import os
import pandas as pd

def read_csv_files(directory):
    data_frames = []
    
    for filename in os.listdir(directory):
        if filename.endswith(".csv"):
            file_path = os.path.join(directory, filename)
            original_df = pd.read_csv(file_path)
            
            if len(original_df.columns) == 1:
                first_column_name = original_df.columns[0]
                column_names = first_column_name.split()

                split_columns = original_df.iloc[:, 0].str.split(expand=True)
                new_df = pd.concat([original_df, split_columns], axis=1)
                new_df = new_df.drop(new_df.columns[0], axis=1)
                new_df.columns = column_names
                original_df = new_df
            
            original_df['Station'] = filename.split('.')[0]
            data_frames.append(original_df)
            
    return data_frames

csv_directory = '/Users/roshanchandru/Desktop/Dissertation/Dataset/Germany/Indicies/CWD'

dataframes = read_csv_files(csv_directory)
dataframes

[    year   cwd      Station
 0   1901   5.0  61700004063
 1   1902   6.0  61700004063
 2   1903   5.0  61700004063
 3   1904   6.0  61700004063
 4   1905   6.0  61700004063
 ..   ...   ...          ...
 94  1995  10.0  61700004063
 95  1996   7.0  61700004063
 96  1997   7.0  61700004063
 97  1998   9.0  61700004063
 98  1999   6.0  61700004063

 [99 rows x 3 columns],
      year   cwd      Station
 0    1879 -99.9  LOCID000043
 1    1880 -99.9  LOCID000043
 2    1881 -99.9  LOCID000043
 3    1882 -99.9  LOCID000043
 4    1883 -99.9  LOCID000043
 ..    ...   ...          ...
 121  2000  10.0  LOCID000043
 122  2001   9.0  LOCID000043
 123  2002   9.0  LOCID000043
 124  2003   6.0  LOCID000043
 125  2004  11.0  LOCID000043

 [126 rows x 3 columns],
      year   cwd      Station
 0    1879 -99.9  LOCID000042
 1    1880 -99.9  LOCID000042
 2    1881 -99.9  LOCID000042
 3    1882 -99.9  LOCID000042
 4    1883 -99.9  LOCID000042
 ..    ...   ...          ...
 121  2000  10.0  LOCID000042
 122  2001   9.0  LOCID000042
 123  2002   9.0  LOCID000042
 124  2003   6.0  LOCID000042
 125  2004  11.0  LOCID000042

 [126 rows x 3 columns],
      year   cwd      Station
 0    1870   7.0  LOCID000040
 1    1871   6.0  LOCID000040
 2    1872   9.0  LOCID000040
 3    1873   6.0  LOCID000040
 4    1874  10.0  LOCID000040
 ..    ...   ...          ...
 130  2000  10.0  LOCID000040
 131  2001   9.0  LOCID000040
 132  2002   7.0  LOCID000040
 133  2003   5.0  LOCID000040
 134  2004   4.0  LOCID000040

 [135 rows x 3 columns],
      year   cwd      Station
 0    1879 -99.9  LOCID000054
 1    1880 -99.9  LOCID000054
 2    1881 -99.9  LOCID000054
 3    1882 -99.9  LOCID000054
 4    1883 -99.9  LOCID000054
 ..    ...   ...          ...
 121  2000  11.0  LOCID000054
 122  2001  19.0  LOCID000054
 123  2002 -99.9  LOCID000054
 124  2003 -99.9  LOCID000054
 125  2004 -99.9  LOCID000054

 [126 rows x 3 columns],
      year   cwd      Station
 0    1870 -99.9  LOCID000041
 1    1871 -99.9  LOCID000041
 2    1872 -99.9  LOCID000041
 3    1873 -99.9  LOCID000041
 4    1874 -99.9  LOCID000041
 ..    ...   ...          ...
 130  2000   5.0  LOCID000041
 131  2001   6.0  LOCID000041
 132  2002   4.0  LOCID000041
 133  2003   5.0  LOCID000041
 134  2004   5.0  LOCID000041

 [135 rows x 3 columns],
     year   cwd      Station
 0   1912   9.0  61700003865
 1   1913   6.0  61700003865
 2   1914   5.0  61700003865
 3   1915  11.0  61700003865
 4   1916  14.0  61700003865
 5   1917   6.0  61700003865
 6   1918   7.0  61700003865
 7   1919   7.0  61700003865
 8   1920   9.0  61700003865
 9   1921   7.0  61700003865
 10  1922   6.0  61700003865
 11  1923  11.0  61700003865
 12  1924   7.0  61700003865
 13  1925  11.0  61700003865
 14  1926  10.0  61700003865
 15  1927   8.0  61700003865
 16  1928   7.0  61700003865
 17  1929   7.0  61700003865
 18  1930   8.0  61700003865
 19  1931   9.0  61700003865
 20  1932  11.0  61700003865
 21  1933   8.0  61700003865
 22  1934  10.0  61700003865
 23  1935   7.0  61700003865
 24  1936   9.0  61700003865
 25  1937   9.0  61700003865
 26  1938   8.0  61700003865
 27  1939   8.0  61700003865
 28  1940   7.0  61700003865
 29  1941  13.0  61700003865
 30  1942   5.0  61700003865
 31  1943  11.0  61700003865
 32  1944   9.0  61700003865
 33  1945   8.0  61700003865
 34  1946  10.0  61700003865
 35  1947   9.0  61700003865
 36  1948  12.0  61700003865
 37  1949   7.0  61700003865
 38  1950   5.0  61700003865
 39  1951   7.0  61700003865
 40  1952   7.0  61700003865
 41  1953   8.0  61700003865
 42  1954  11.0  61700003865
 43  1955   9.0  61700003865
 44  1956   6.0  61700003865
 45  1957   9.0  61700003865
 46  1958   9.0  61700003865
 47  1959   6.0  61700003865
 48  1960   8.0  61700003865
 49  1961  10.0  61700003865
 50  1962 -99.9  61700003865,
      year   cwd      Station
 0    1879 -99.9  LOCID000045
 1    1880 -99.9  LOCID000045
 2    1881 -99.9  LOCID000045
 3    1882 -99.9  LOCID000045
 4    1883 -99.9  LOCID000045
 ..    ...   ...          ...
 121  2000   5.0  LOCID000045
 122  2001   6.0  LOCID000045
 123  2002 -99.9  LOCID000045
 124  2003 -99.9  LOCID000045
 125  2004 -99.9  LOCID000045

 [126 rows x 3 columns],
      year   cwd      Station
 0    1879 -99.9  LOCID000051
 1    1880 -99.9  LOCID000051
 2    1881 -99.9  LOCID000051
 3    1882 -99.9  LOCID000051
 4    1883 -99.9  LOCID000051
 ..    ...   ...          ...
 121  2000  11.0  LOCID000051
 122  2001   7.0  LOCID000051
 123  2002   6.0  LOCID000051
 124  2003   8.0  LOCID000051
 125  2004   8.0  LOCID000051

 [126 rows x 3 columns],
      year  cwd      Station
 0    1879    6  LOCID000050
 1    1880    9  LOCID000050
 2    1881   13  LOCID000050
 3    1882    7  LOCID000050
 4    1883    7  LOCID000050
 ..    ...  ...          ...
 121  2000    6  LOCID000050
 122  2001    7  LOCID000050
 123  2002    8  LOCID000050
 124  2003    9  LOCID000050
 125  2004    9  LOCID000050

 [126 rows x 3 columns],
      year   cwd      Station
 0    1879   9.0  LOCID000044
 1    1880   6.0  LOCID000044
 2    1881   7.0  LOCID000044
 3    1882  12.0  LOCID000044
 4    1883  16.0  LOCID000044
 ..    ...   ...          ...
 121  2000  11.0  LOCID000044
 122  2001  10.0  LOCID000044
 123  2002 -99.9  LOCID000044
 124  2003 -99.9  LOCID000044
 125  2004 -99.9  LOCID000044

 [126 rows x 3 columns],
     year   cwd      Station
 0   1901   7.0  61700003319
 1   1902   6.0  61700003319
 2   1903   5.0  61700003319
 3   1904   5.0  61700003319
 4   1905   6.0  61700003319
 ..   ...   ...          ...
 94  1995  12.0  61700003319
 95  1996   7.0  61700003319
 96  1997   6.0  61700003319
 97  1998   8.0  61700003319
 98  1999   5.0  61700003319

 [99 rows x 3 columns],
      year   cwd      Station
 0    1879 -99.9  LOCID000052
 1    1880 -99.9  LOCID000052
 2    1881 -99.9  LOCID000052
 3    1882 -99.9  LOCID000052
 4    1883 -99.9  LOCID000052
 ..    ...   ...          ...
 121  2000   5.0  LOCID000052
 122  2001  11.0  LOCID000052
 123  2002   5.0  LOCID000052
 124  2003   5.0  LOCID000052
 125  2004  11.0  LOCID000052

 [126 rows x 3 columns],
      year   cwd      Station
 0    1879 -99.9  LOCID000046
 1    1880 -99.9  LOCID000046
 2    1881 -99.9  LOCID000046
 3    1882 -99.9  LOCID000046
 4    1883 -99.9  LOCID000046
 ..    ...   ...          ...
 121  2000 -99.9  LOCID000046
 122  2001 -99.9  LOCID000046
 123  2002 -99.9  LOCID000046
 124  2003 -99.9  LOCID000046
 125  2004 -99.9  LOCID000046

 [126 rows x 3 columns],
      year   cwd      Station
 0    1876  17.0  LOCID000047
 1    1877  12.0  LOCID000047
 2    1878   9.0  LOCID000047
 3    1879   9.0  LOCID000047
 4    1880   8.0  LOCID000047
 ..    ...   ...          ...
 124  2000   7.0  LOCID000047
 125  2001   9.0  LOCID000047
 126  2002 -99.9  LOCID000047
 127  2003 -99.9  LOCID000047
 128  2004 -99.9  LOCID000047

 [129 rows x 3 columns],
      year   cwd      Station
 0    1879 -99.9  LOCID000053
 1    1880 -99.9  LOCID000053
 2    1881 -99.9  LOCID000053
 3    1882 -99.9  LOCID000053
 4    1883 -99.9  LOCID000053
 ..    ...   ...          ...
 121  2000 -99.9  LOCID000053
 122  2001 -99.9  LOCID000053
 123  2002 -99.9  LOCID000053
 124  2003 -99.9  LOCID000053
 125  2004 -99.9  LOCID000053

 [126 rows x 3 columns],
     year  cwd      Station
 0   1917    6  61700003244
 1   1918    5  61700003244
 2   1919    9  61700003244
 3   1920    9  61700003244
 4   1921    8  61700003244
 ..   ...  ...          ...
 78  1995    8  61700003244
 79  1996    4  61700003244
 80  1997    9  61700003244
 81  1998   11  61700003244
 82  1999    6  61700003244

 [83 rows x 3 columns],
     year   cwd      Station
 0   1901   7.0  61700002698
 1   1902   6.0  61700002698
 2   1903   6.0  61700002698
 3   1904  10.0  61700002698
 4   1905  16.0  61700002698
 ..   ...   ...          ...
 94  1995  11.0  61700002698
 95  1996   7.0  61700002698
 96  1997  10.0  61700002698
 97  1998   9.0  61700002698
 98  1999   5.0  61700002698

 [99 rows x 3 columns],
     year    cwd      Station
 0   1901    7.0  61700002288
 1   1902    9.0  61700002288
 2   1903    7.0  61700002288
 3   1904   13.0  61700002288
 4   1905    6.0  61700002288
 ..   ...    ...          ...
 94  1995  -99.9  61700002288
 95  1996  -99.9  61700002288
 96  1997  -99.9  61700002288
 97  1998  -99.9  61700002288
 98  1999    9.0  61700002288

 [99 rows x 3 columns],
     year    cwd      Station
 0   1907  -99.9  61700002277
 1   1908    9.0  61700002277
 2   1909   11.0  61700002277
 3   1910   10.0  61700002277
 4   1911    6.0  61700002277
 ..   ...    ...          ...
 88  1995   10.0  61700002277
 89  1996  -99.9  61700002277
 90  1997    6.0  61700002277
 91  1998   11.0  61700002277
 92  1999  -99.9  61700002277

 [93 rows x 3 columns],
     year  cwd      Station
 0   1901    5  61700003342
 1   1902    6  61700003342
 2   1903    7  61700003342
 3   1904    5  61700003342
 4   1905   10  61700003342
 ..   ...  ...          ...
 94  1995    7  61700003342
 95  1996    7  61700003342
 96  1997    6  61700003342
 97  1998   11  61700003342
 98  1999    6  61700003342

 [99 rows x 3 columns],
     year   cwd      Station
 0   1901   6.0  61700001153
 1   1902  11.0  61700001153
 2   1903   7.0  61700001153
 3   1904   7.0  61700001153
 4   1905  11.0  61700001153
 ..   ...   ...          ...
 86  1987   9.0  61700001153
 87  1988   9.0  61700001153
 88  1989   7.0  61700001153
 89  1990   8.0  61700001153
 90  1991   7.0  61700001153

 [91 rows x 3 columns],
      year  cwd      Station
 0    1876   13  LOCID000037
 1    1877    8  LOCID000037
 2    1878    8  LOCID000037
 3    1879    6  LOCID000037
 4    1880    9  LOCID000037
 ..    ...  ...          ...
 124  2000    6  LOCID000037
 125  2001    6  LOCID000037
 126  2002    8  LOCID000037
 127  2003    9  LOCID000037
 128  2004    9  LOCID000037

 [129 rows x 3 columns],
      year  cwd      Station
 0    1879    8  LOCID000036
 1    1880   10  LOCID000036
 2    1881    5  LOCID000036
 3    1882   12  LOCID000036
 4    1883    7  LOCID000036
 ..    ...  ...          ...
 121  2000    7  LOCID000036
 122  2001    6  LOCID000036
 123  2002    7  LOCID000036
 124  2003    4  LOCID000036
 125  2004    5  LOCID000036

 [126 rows x 3 columns],
     year   cwd      Station
 0   1901   6.0  61700004204
 1   1902   5.0  61700004204
 2   1903   8.0  61700004204
 3   1904   6.0  61700004204
 4   1905   6.0  61700004204
 ..   ...   ...          ...
 94  1995   6.0  61700004204
 95  1996   6.0  61700004204
 96  1997 -99.9  61700004204
 97  1998   5.0  61700004204
 98  1999   5.0  61700004204

 [99 rows x 3 columns],
     year   cwd      Station
 0   1901   7.0  61700004199
 1   1902   7.0  61700004199
 2   1903   7.0  61700004199
 3   1904   5.0  61700004199
 4   1905   8.0  61700004199
 ..   ...   ...          ...
 94  1995   8.0  61700004199
 95  1996   8.0  61700004199
 96  1997   8.0  61700004199
 97  1998  10.0  61700004199
 98  1999 -99.9  61700004199

 [99 rows x 3 columns],
     year   cwd      Station
 0   1901   5.0  61700003218
 1   1902   5.0  61700003218
 2   1903   4.0  61700003218
 3   1904   3.0  61700003218
 4   1905   6.0  61700003218
 ..   ...   ...          ...
 85  1986  11.0  61700003218
 86  1987   7.0  61700003218
 87  1988   8.0  61700003218
 88  1989   6.0  61700003218
 89  1990 -99.9  61700003218

 [90 rows x 3 columns],
     year   cwd      Station
 0   1901   6.0  61700002716
 1   1902   7.0  61700002716
 2   1903   6.0  61700002716
 3   1904   5.0  61700002716
 4   1905  10.0  61700002716
 ..   ...   ...          ...
 94  1995   8.0  61700002716
 95  1996   7.0  61700002716
 96  1997   6.0  61700002716
 97  1998   9.0  61700002716
 98  1999   8.0  61700002716

 [99 rows x 3 columns],
     year   cwd      Station
 0   1901   9.0  61700004155
 1   1902  17.0  61700004155
 2   1903  10.0  61700004155
 3   1904  11.0  61700004155
 4   1905  15.0  61700004155
 ..   ...   ...          ...
 94  1995  13.0  61700004155
 95  1996  11.0  61700004155
 96  1997  10.0  61700004155
 97  1998  12.0  61700004155
 98  1999  10.0  61700004155

 [99 rows x 3 columns],
     year   cwd      Station
 0   1901   6.0  61700002641
 1   1902   9.0  61700002641
 2   1903   6.0  61700002641
 3   1904   9.0  61700002641
 4   1905   4.0  61700002641
 ..   ...   ...          ...
 94  1995   6.0  61700002641
 95  1996   6.0  61700002641
 96  1997   7.0  61700002641
 97  1998  13.0  61700002641
 98  1999   7.0  61700002641

 [99 rows x 3 columns],
      year   cwd      Station
 0    1879 -99.9  LOCID000038
 1    1880 -99.9  LOCID000038
 2    1881 -99.9  LOCID000038
 3    1882 -99.9  LOCID000038
 4    1883 -99.9  LOCID000038
 ..    ...   ...          ...
 121  2000   9.0  LOCID000038
 122  2001  11.0  LOCID000038
 123  2002  10.0  LOCID000038
 124  2003   8.0  LOCID000038
 125  2004   8.0  LOCID000038

 [126 rows x 3 columns],
      year   cwd      Station
 0    1879 -99.9  LOCID000039
 1    1880 -99.9  LOCID000039
 2    1881 -99.9  LOCID000039
 3    1882 -99.9  LOCID000039
 4    1883 -99.9  LOCID000039
 ..    ...   ...          ...
 121  2000   5.0  LOCID000039
 122  2001   4.0  LOCID000039
 123  2002   5.0  LOCID000039
 124  2003   5.0  LOCID000039
 125  2004   7.0  LOCID000039

 [126 rows x 3 columns],
     year   cwd      Station
 0   1901   6.0  61700003038
 1   1902   5.0  61700003038
 2   1903  11.0  61700003038
 3   1904   9.0  61700003038
 4   1905   6.0  61700003038
 ..   ...   ...          ...
 94  1995   6.0  61700003038
 95  1996   5.0  61700003038
 96  1997   5.0  61700003038
 97  1998  10.0  61700003038
 98  1999   7.0  61700003038

 [99 rows x 3 columns],
      year  cwd      Station
 0    1879    9  61700010962
 1    1880    6  61700010962
 2    1881    8  61700010962
 3    1882   12  61700010962
 4    1883   16  61700010962
 ..    ...  ...          ...
 116  1995   10  61700010962
 117  1996    8  61700010962
 118  1997   11  61700010962
 119  1998    9  61700010962
 120  1999   11  61700010962

 [121 rows x 3 columns],
      year   cwd      Station
 0    1879 -99.9  LOCID000049
 1    1880 -99.9  LOCID000049
 2    1881 -99.9  LOCID000049
 3    1882 -99.9  LOCID000049
 4    1883 -99.9  LOCID000049
 ..    ...   ...          ...
 121  2000   7.0  LOCID000049
 122  2001   7.0  LOCID000049
 123  2002   6.0  LOCID000049
 124  2003   5.0  LOCID000049
 125  2004  12.0  LOCID000049

 [126 rows x 3 columns],
      year   cwd      Station
 0    1879   6.0  LOCID000048
 1    1880   8.0  LOCID000048
 2    1881   6.0  LOCID000048
 3    1882  11.0  LOCID000048
 4    1883  19.0  LOCID000048
 ..    ...   ...          ...
 121  2000   7.0  LOCID000048
 122  2001  10.0  LOCID000048
 123  2002   7.0  LOCID000048
 124  2003  10.0  LOCID000048
 125  2004   8.0  LOCID000048

 [126 rows x 3 columns],
     year   cwd      Station
 0   1901   6.0  61700001474
 1   1902  11.0  61700001474
 2   1903   7.0  61700001474
 3   1904   7.0  61700001474
 4   1905   7.0  61700001474
 ..   ...   ...          ...
 94  1995   8.0  61700001474
 95  1996   7.0  61700001474
 96  1997   7.0  61700001474
 97  1998  10.0  61700001474
 98  1999   5.0  61700001474

 [99 rows x 3 columns],
      year  cwd      Station
 0    1891   17  61700010147
 1    1892   10  61700010147
 2    1893   13  61700010147
 3    1894   15  61700010147
 4    1895    8  61700010147
 ..    ...  ...          ...
 104  1995   10  61700010147
 105  1996   10  61700010147
 106  1997    8  61700010147
 107  1998   10  61700010147
 108  1999   10  61700010147

 [109 rows x 3 columns]]

In [2]:
for i, df in enumerate(dataframes, start=1):
    print(f"Shape of csv{i}:", df.shape)

Shape of csv1: (99, 3)
Shape of csv2: (126, 3)
Shape of csv3: (126, 3)
Shape of csv4: (135, 3)
Shape of csv5: (126, 3)
Shape of csv6: (135, 3)
Shape of csv7: (51, 3)
Shape of csv8: (126, 3)
Shape of csv9: (126, 3)
Shape of csv10: (126, 3)
Shape of csv11: (126, 3)
Shape of csv12: (99, 3)
Shape of csv13: (126, 3)
Shape of csv14: (126, 3)
Shape of csv15: (129, 3)
Shape of csv16: (126, 3)
Shape of csv17: (83, 3)
Shape of csv18: (99, 3)
Shape of csv19: (99, 3)
Shape of csv20: (93, 3)
Shape of csv21: (99, 3)
Shape of csv22: (91, 3)
Shape of csv23: (129, 3)
Shape of csv24: (126, 3)
Shape of csv25: (99, 3)
Shape of csv26: (99, 3)
Shape of csv27: (90, 3)
Shape of csv28: (99, 3)
Shape of csv29: (99, 3)
Shape of csv30: (99, 3)
Shape of csv31: (126, 3)
Shape of csv32: (126, 3)
Shape of csv33: (99, 3)
Shape of csv34: (121, 3)
Shape of csv35: (126, 3)
Shape of csv36: (126, 3)
Shape of csv37: (99, 3)
Shape of csv38: (109, 3)

In [3]:
print(type(dataframes))

<class 'list'>

In [4]:
import pandas as pd

def merge_csv_files(file_paths):
    dfs = []

    for file_path in file_paths:
        df = pd.read_csv(file_path)
        dfs.append(df)


    merged_df_CWD = pd.concat(dfs, ignore_index=True)
    return merged_df_CWD

merged_df_T = pd.concat(dataframes, ignore_index=True)
merged_df_TXx

NameError: name 'merged_df_TXx' is not defined

In [ ]:
merged_df_TXx.head(30)

In [ ]:
merged_df_TXx.to_csv('merged_df_TXx.csv', index=False)