In [1]:
import os
import pandas as pd

def read_csv_files(directory):
    data_frames = []
    
    for filename in os.listdir(directory):
        if filename.endswith(".csv"):
            file_path = os.path.join(directory, filename)
            original_df = pd.read_csv(file_path)
            
            if len(original_df.columns) == 1:
                first_column_name = original_df.columns[0]
                column_names = first_column_name.split()

                split_columns = original_df.iloc[:, 0].str.split(expand=True)
                new_df = pd.concat([original_df, split_columns], axis=1)
                new_df = new_df.drop(new_df.columns[0], axis=1)
                new_df.columns = column_names
                original_df = new_df
            
            original_df['Station'] = filename.split('.')[0]
            data_frames.append(original_df)
            
    return data_frames

csv_directory = '/Users/roshanchandru/Desktop/Dissertation/Dataset/Germany/Indicies/RX1day'

dataframes = read_csv_files(csv_directory)
dataframes

[    year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0   1901  23.1   8.2  11.2   6.4  11.7  31.4  41.9  51.7  16.9  22.3   7.7
 1   1902   6.5   8.6   8.7   6.1  13.2  17.0  13.6  14.9   8.2  21.8   4.9
 2   1903  24.2   2.5   4.7   6.6  11.6  11.7  15.2  14.8   9.5  20.6   9.7
 3   1904   8.3  16.1  15.9   7.8  17.0  18.1  10.1  14.2  18.6  16.6  17.5
 4   1905  14.4   5.1  18.1   9.3   5.4  26.4  24.1  13.1   9.8   8.6  17.6
 ..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 94  1995  39.3  21.4  19.0   6.6  15.2  10.7  36.0  29.4  13.6  11.2  12.9
 95  1996   0.5   9.1   4.9   7.2  15.1  17.9  53.7  37.8   9.6  12.1   7.2
 96  1997  19.6  25.7   5.8   4.2   8.4  19.5  23.0  12.4   9.3   6.5  13.3
 97  1998  11.5   4.5   6.3  10.0   9.8  18.7   5.5   8.9  23.5  27.3  12.0
 98  1999  11.2   7.2   5.9   9.5  14.6  24.5  37.6  14.1   7.3   6.7  11.3

      dec  annual      Station
 0    8.2    51.7  61700004063
 1   20.6    21.8  61700004063
 2    5.0    24.2  61700004063
 3    9.0    18.6  61700004063
 4    7.8    26.4  61700004063
 ..   ...     ...          ...
 94  14.4    39.3  61700004063
 95  11.7    53.7  61700004063
 96  11.7    25.7  61700004063
 97   6.2    27.3  61700004063
 98  17.5    37.6  61700004063

 [99 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000  14.1   9.2  18.5   5.4   7.5  12.4   8.1  35.8  10.8   5.7   5.9
 122  2001   7.7   7.8  16.4  13.2  19.9  24.1  13.6  22.4  30.6  12.6   7.8
 123  2002  11.0  22.0  19.0  13.0  14.0  18.0  50.0  33.0   6.0  34.0  26.0
 124  2003  12.0   3.0  16.0  10.0  19.0  15.0  14.0  23.0  24.0   9.0  17.0
 125  2004  13.0  24.0  10.0   7.0   7.0  23.0  19.0  16.0  25.0   6.0  22.0

       dec  annual      Station
 0   -99.9   -99.9  LOCID000043
 1   -99.9   -99.9  LOCID000043
 2   -99.9   -99.9  LOCID000043
 3   -99.9   -99.9  LOCID000043
 4   -99.9   -99.9  LOCID000043
 ..    ...     ...          ...
 121  17.6    35.8  LOCID000043
 122  16.2    30.6  LOCID000043
 123   5.0    50.0  LOCID000043
 124  22.0    24.0  LOCID000043
 125   7.0    25.0  LOCID000043

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000  14.1   9.2  18.5   5.4   7.5  12.4   8.1  35.8  10.8   5.7   5.9
 122  2001   7.7   7.8  16.4  13.2  19.9  24.1  13.6  22.4  30.6  12.6   7.8
 123  2002  11.0  22.0  19.0  13.0   9.0  18.0  50.0  33.0   6.0  34.0  26.0
 124  2003  12.0   3.0  16.0  10.0  19.0  15.0  14.0  23.0  24.0   9.0  17.0
 125  2004  13.0  24.0  10.0   7.0   7.0  23.0  19.0  16.0  25.0   6.0  22.0

       dec  annual      Station
 0   -99.9   -99.9  LOCID000042
 1   -99.9   -99.9  LOCID000042
 2   -99.9   -99.9  LOCID000042
 3   -99.9   -99.9  LOCID000042
 4   -99.9   -99.9  LOCID000042
 ..    ...     ...          ...
 121  17.6    35.8  LOCID000042
 122  16.2    30.6  LOCID000042
 123   5.0    50.0  LOCID000042
 124  22.0    24.0  LOCID000042
 125   7.0    25.0  LOCID000042

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1870   7.9   3.1  16.2   2.6   7.0   6.3  59.7  62.8  19.1  22.3   8.3
 1    1871  17.4  12.0   5.1  33.2   2.8  32.7  32.7  19.0  19.4  16.8   6.2
 2    1872  12.1   9.4  10.7  26.6  17.5  24.5  11.3  13.9  19.2  13.0  24.2
 3    1873  15.1  10.2   9.5  10.8   9.8  15.5  34.5  24.5   7.3  35.0   4.3
 4    1874   6.1   5.3   4.2   7.7  20.6  16.5  20.5  17.2  17.1  11.8  12.2
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 130  2000  14.0  10.0  24.0   7.0  44.0   8.0  18.0  18.0  14.0  10.0  13.0
 131  2001  18.0  15.0  17.0   9.0  10.0  13.0   8.0  31.0  18.0  12.0  26.0
 132  2002  13.0  19.0  13.0   9.0  22.0   8.0  45.0  27.0   9.0  12.0  18.0
 133  2003  19.0   6.0   6.0   4.0  24.0   8.0   6.0   5.0  17.0   9.0  10.0
 134  2004  15.0   8.0   5.0   9.0  25.0  12.0  38.0  14.0  25.0   7.0  10.0

       dec  annual      Station
 0    15.5    62.8  LOCID000040
 1     6.6    33.2  LOCID000040
 2    14.1    26.6  LOCID000040
 3     1.9    35.0  LOCID000040
 4     9.3    20.6  LOCID000040
 ..    ...     ...          ...
 130  11.0    44.0  LOCID000040
 131   9.0    31.0  LOCID000040
 132  18.0    45.0  LOCID000040
 133  13.0    24.0  LOCID000040
 134   6.0    38.0  LOCID000040

 [135 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000  40.6  36.9  81.0  43.8  32.2  20.4  51.8  37.4  36.6  31.0  17.6
 122  2001  15.4  48.0  28.0  36.0  29.5  55.9  39.2  37.7  63.3  14.1  35.1
 123  2002 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 124  2003 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 125  2004 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9  17.0  39.0

       dec  annual      Station
 0   -99.9   -99.9  LOCID000054
 1   -99.9   -99.9  LOCID000054
 2   -99.9   -99.9  LOCID000054
 3   -99.9   -99.9  LOCID000054
 4   -99.9   -99.9  LOCID000054
 ..    ...     ...          ...
 121  18.1    81.0  LOCID000054
 122  29.4    63.3  LOCID000054
 123 -99.9   -99.9  LOCID000054
 124 -99.9   -99.9  LOCID000054
 125  23.0   -99.9  LOCID000054

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1870 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1871 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1872 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1873 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1874 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 130  2000   8.0  16.0   9.0   4.0   7.0  15.0  21.0  15.0  12.0  12.0   4.0
 131  2001   5.0   6.0  18.0   8.0  14.0   8.0  57.0   9.0  17.0   5.0  10.0
 132  2002   7.0   6.0  11.0  18.0  17.0  26.0  34.0  53.0  30.0   9.0  26.0
 133  2003  13.0   3.0   7.0   7.0   7.0  20.0  17.0  14.0  34.0   9.0  14.0
 134  2004   7.0  10.0   8.0   6.0  13.0  28.0  30.0  17.0   5.0   3.0  26.0

       dec  annual      Station
 0   -99.9   -99.9  LOCID000041
 1   -99.9   -99.9  LOCID000041
 2   -99.9   -99.9  LOCID000041
 3   -99.9   -99.9  LOCID000041
 4   -99.9   -99.9  LOCID000041
 ..    ...     ...          ...
 130   5.0    21.0  LOCID000041
 131  13.0    57.0  LOCID000041
 132  25.0    53.0  LOCID000041
 133  12.0    34.0  LOCID000041
 134   7.0    30.0  LOCID000041

 [135 rows x 15 columns],
     year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0   1912  16.0   6.9   8.0   7.1  25.1  35.4  12.0   9.9  15.2   8.4  15.8
 1   1913   8.9  10.8   6.5   8.0   9.5  11.1  32.8   9.5   5.6  11.4  10.3
 2   1914   8.9  10.6  23.2  12.6  11.6  10.7  53.0  16.3  65.1  13.5  25.8
 3   1915  14.0   3.9  25.6   9.3  12.8  19.4  23.4  25.3   9.4   7.6  10.1
 4   1916  17.8  15.1   4.5  15.2  15.1  10.2  12.0  21.5  26.6  18.7   9.2
 5   1917   7.9   4.5   7.9  11.7   2.0  13.6  22.0  13.3   7.0  23.3  12.5
 6   1918  14.3  14.0   4.5  15.0  12.2  24.1  21.4  36.8  11.6   9.0   3.8
 7   1919   7.5   7.4  11.1   7.2   4.9   6.9  16.6  17.1   7.2   9.2  11.7
 8   1920  11.8   7.3   5.5   9.7  26.8  10.3  14.5  14.3  10.8   4.4   7.1
 9   1921  18.2  17.2   4.4  11.4   9.1  14.5  16.9  30.0  12.0   9.3  15.7
 10  1922  23.1   9.6  11.5   6.7  17.4   8.2  38.1  24.8  10.4  11.5  14.0
 11  1923   9.6   9.7   8.9   9.6  18.2   9.9  31.2  15.5  11.7   8.8  10.0
 12  1924   7.8  20.8   3.0  23.3  24.2  32.0  17.4  13.1   9.3  15.3   8.0
 13  1925  10.1  12.1  23.8   8.1   6.9  14.0  16.6  14.8  24.7  15.7  19.8
 14  1926  11.0  14.9  14.0   6.9  16.3  36.8  67.9  16.5  12.4  16.0  19.1
 15  1927   8.3   9.0  10.5  12.6  14.7  11.5  25.8  35.6  29.1  15.9  12.4
 16  1928  19.6  13.1   7.2  12.1  30.9   7.3   9.8  20.6   2.8  12.8  21.0
 17  1929   9.1  11.1   2.4  11.0  27.5  29.7  14.7  10.8  19.3  33.1  15.4
 18  1930   8.3   5.7   7.5  10.0  14.2   9.1   9.5  39.6  28.1  14.9  16.4
 19  1931  19.7  13.9  12.3  13.5  34.4  15.3  35.7  19.8  28.6   6.9   4.5
 20  1932  15.3   3.9   6.8  23.6  16.4   6.0  13.2  34.0  17.4  15.4   9.1
 21  1933   6.0  11.1  16.2  12.0  12.6  36.1  11.4  36.0   7.9  23.5   7.2
 22  1934   9.2  12.4  12.3   2.9   5.2  25.3  10.0  27.4   9.3  14.6  44.2
 23  1935   9.7  20.3   8.6  12.8  23.3  47.2  15.5  12.1  18.1   8.7  11.1
 24  1936   7.5  11.4   5.1  34.6  11.0  21.4  20.7  24.3  12.2  13.2  17.1
 25  1937  11.8  16.5  12.1  20.2  10.7  35.2  22.3  37.0  30.1   8.4   4.7
 26  1938  15.2  10.6   6.8   4.9  20.7  12.4  30.9  28.9  10.1  13.4  11.4
 27  1939   9.0   6.4  13.9  18.6   7.7  18.0  48.9  14.8   7.5  60.8  13.7
 28  1940   7.2   8.9  18.0  16.1  16.5   7.2  13.4  33.6  10.0  18.2  16.4
 29  1941   8.1  11.2   8.0   6.6  33.9  14.2  59.3  15.5  10.7  36.0   9.9
 30  1942   8.8   5.6   5.8  11.8   6.2  19.3  30.1  17.3  16.5  12.1  11.5
 31  1943   9.7  13.4   3.7  11.4   9.8  11.5  13.8  24.2   9.0  15.2  14.0
 32  1944   9.7  14.2  10.5  15.4  11.6  18.5   9.7   4.5   8.6   9.2  17.0
 33  1945   7.5  15.5   9.4  13.3  12.9  13.1  44.7  41.7   9.0   6.4  11.4
 34  1946  27.3   8.0  35.4   3.4  16.9  19.5  15.5  27.2  13.6  20.4  17.9
 35  1947   4.7   6.6  15.1  13.5  21.5   8.9  15.5   7.7  14.6  11.8  22.5
 36  1948  19.6  26.7   8.3   6.0  25.8   8.5  42.5  35.9  13.5   5.1   4.5
 37  1949   7.8   8.5  10.8  26.3  14.2  25.6   6.2  13.7  25.0   3.3  19.4
 38  1950  24.0  16.5   8.0  16.8  12.0   6.4  31.1  10.5  13.2   5.6  13.7
 39  1951  14.6  10.5  24.7   7.6  37.7  24.3  25.2  25.9  18.3   1.6  23.8
 40  1952   6.0   7.5  11.3   4.8  12.3  13.2   8.2  18.4   8.8  16.2  14.8
 41  1953  13.6   6.8   7.8  10.0   8.7  25.8  12.9  32.5   6.0   2.7  18.6
 42  1954   6.1   6.5  10.8  13.9  18.5  17.2  18.4  40.0  12.4  11.4  36.2
 43  1955  30.0   9.7  10.5   6.2   8.1  15.4  33.6   9.5  19.1  31.6   5.1
 44  1956  28.9   7.1  13.8   7.5   7.6  10.9  25.0  21.4   8.1  13.9  13.3
 45  1957  11.8  15.8  12.3   7.8  19.1  24.6  11.6  12.0  16.8   7.4  12.2
 46  1958  13.8  12.5   7.1   9.1  16.0  11.2  18.0  17.4  28.1  26.8   7.1
 47  1959  11.8   5.1   4.2   4.1  19.6  12.8   5.3  20.1   1.2   8.6  11.3
 48  1960  14.5   7.0   6.5   6.8  10.8  29.2  22.1  35.3  20.1  10.4  21.7
 49  1961  10.2  26.5  13.6   9.6  21.8  10.0  22.8  32.6   7.2  10.7  11.7
 50  1962  12.8  18.3   9.8  10.0  19.6   8.1  16.6  18.6  15.9 -99.9 -99.9

      dec  annual      Station
 0   10.2    35.4  61700003865
 1   17.1    32.8  61700003865
 2   21.4    65.1  61700003865
 3   14.9    25.6  61700003865
 4   15.4    26.6  61700003865
 5   16.3    23.3  61700003865
 6   16.3    36.8  61700003865
 7   14.9    17.1  61700003865
 8    9.2    26.8  61700003865
 9   17.3    30.0  61700003865
 10  17.3    38.1  61700003865
 11   9.2    31.2  61700003865
 12  10.8    32.0  61700003865
 13  25.0    25.0  61700003865
 14  11.0    67.9  61700003865
 15  11.9    35.6  61700003865
 16   6.5    30.9  61700003865
 17  18.7    33.1  61700003865
 18   3.7    39.6  61700003865
 19  18.6    35.7  61700003865
 20   5.2    34.0  61700003865
 21   6.5    36.1  61700003865
 22   9.9    44.2  61700003865
 23   4.5    47.2  61700003865
 24  12.3    34.6  61700003865
 25   9.8    37.0  61700003865
 26  12.3    30.9  61700003865
 27  15.7    60.8  61700003865
 28  13.2    33.6  61700003865
 29   8.1    59.3  61700003865
 30  12.8    30.1  61700003865
 31   8.0    24.2  61700003865
 32  12.8    18.5  61700003865
 33  23.0    44.7  61700003865
 34   4.2    35.4  61700003865
 35  17.4    22.5  61700003865
 36   5.0    42.5  61700003865
 37  21.0    26.3  61700003865
 38  11.8    31.1  61700003865
 39  14.4    37.7  61700003865
 40   9.7    18.4  61700003865
 41   8.5    32.5  61700003865
 42  22.0    40.0  61700003865
 43  14.8    33.6  61700003865
 44  13.6    28.9  61700003865
 45  10.2    24.6  61700003865
 46   6.4    28.1  61700003865
 47   5.2    20.1  61700003865
 48  25.4    35.3  61700003865
 49  25.3    32.6  61700003865
 50 -99.9   -99.9  61700003865  ,
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000   9.5   8.7  12.9  13.6  21.9  14.5  23.8  18.2  15.5  13.1  12.0
 122  2001   4.6   6.3  20.3   4.6  21.1   8.3  59.6   8.6   9.5   8.5  22.9
 123  2002 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 124  2003 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 125  2004 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9

       dec  annual      Station
 0   -99.9   -99.9  LOCID000045
 1   -99.9   -99.9  LOCID000045
 2   -99.9   -99.9  LOCID000045
 3   -99.9   -99.9  LOCID000045
 4   -99.9   -99.9  LOCID000045
 ..    ...     ...          ...
 121   6.5    23.8  LOCID000045
 122  11.9    59.6  LOCID000045
 123 -99.9   -99.9  LOCID000045
 124 -99.9   -99.9  LOCID000045
 125 -99.9   -99.9  LOCID000045

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000  10.2   7.7   7.4   9.8  16.9  12.6  90.5  13.4  22.2   5.8   5.4
 122  2001   8.0   8.3  11.9   8.6   6.0  25.3  12.4  16.4  24.4   5.1  14.2
 123  2002  14.0  25.0  14.0  11.0  13.0  17.0  56.0  19.0   5.0  13.0  17.0
 124  2003  11.0   3.0   9.0   6.0  15.0  21.0  10.0  24.0  21.0   7.0   9.0
 125  2004  10.0  15.0  10.0  11.0  15.0  19.0  12.0  17.0  16.0   8.0  15.0

       dec  annual      Station
 0   -99.9   -99.9  LOCID000051
 1   -99.9   -99.9  LOCID000051
 2   -99.9   -99.9  LOCID000051
 3   -99.9   -99.9  LOCID000051
 4   -99.9   -99.9  LOCID000051
 ..    ...     ...          ...
 121  12.1    90.5  LOCID000051
 122  13.4    25.3  LOCID000051
 123   4.0    56.0  LOCID000051
 124  15.0    24.0  LOCID000051
 125   7.0    19.0  LOCID000051

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879  12.5  16.8  16.9  20.2   9.5   8.4   9.9   9.1   7.6  11.4  13.5
 1    1880   5.3   7.2   4.3   8.5   4.6  32.2  10.5   8.1  16.4  14.4   6.0
 2    1881   7.9   8.6  25.9   2.1  18.3  17.0  11.6  12.7  10.2  12.3   9.7
 3    1882  10.3   5.0   8.3   8.1  18.7  17.6  39.1  12.5  18.1  11.9  14.8
 4    1883  10.3   3.4   1.8  10.5  12.9   1.5  26.2  13.1   8.6  16.5  10.0
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000   8.6   6.9   8.8  15.7  21.8  14.6   8.0  26.8  30.4   7.9   8.4
 122  2001   8.5  10.5  13.8   9.5  11.8  12.1  14.9   8.7  29.0  11.8  10.2
 123  2002  13.0  21.0  12.0  16.0  19.0   7.0  10.0  55.0  24.0  38.0  16.0
 124  2003  16.0   3.0   8.0   7.0   9.0  11.0  11.0  14.0  13.0  10.0  16.0
 125  2004  15.0  12.0  11.0   8.0  17.0  15.0  16.0  11.0   9.0   8.0  17.0

       dec  annual      Station
 0     6.2    20.2  LOCID000050
 1    15.0    32.2  LOCID000050
 2    15.0    25.9  LOCID000050
 3    10.6    39.1  LOCID000050
 4     7.7    26.2  LOCID000050
 ..    ...     ...          ...
 121   8.2    30.4  LOCID000050
 122  11.7    29.0  LOCID000050
 123   8.0    55.0  LOCID000050
 124  15.0    16.0  LOCID000050
 125   7.0    17.0  LOCID000050

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879  14.2  24.4  11.0  23.3  16.8  29.4  17.5  37.4  44.2  23.0  37.5
 1    1880  17.8   6.9  18.7  22.4  22.6  42.3  25.9  33.6  14.7  34.0   9.6
 2    1881   5.9   7.0   7.3   9.8  40.0  35.3  24.1  48.7  24.3  22.7  22.0
 3    1882   9.2   4.7  14.7  20.0  17.5  50.8  33.1  27.3  40.3  18.3  18.1
 4    1883   9.6   4.0  11.3  16.2  34.3  31.7  43.7  26.8  18.4  11.5  28.7
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000   5.4  11.7  61.3  15.2  25.0  35.8  18.0  60.5  53.4  19.1   8.7
 122  2001  26.9  18.7  19.1  17.0  21.4  36.4  22.0  42.2  31.0   9.7  24.3
 123  2002 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 124  2003 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 125  2004 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9  21.0  13.0

       dec  annual      Station
 0    20.1    44.2  LOCID000044
 1    20.7    42.3  LOCID000044
 2     6.6    48.7  LOCID000044
 3     9.4    50.8  LOCID000044
 4    16.3    43.7  LOCID000044
 ..    ...     ...          ...
 121   6.1    61.3  LOCID000044
 122  22.8    42.2  LOCID000044
 123 -99.9   -99.9  LOCID000044
 124 -99.9   -99.9  LOCID000044
 125  25.0   -99.9  LOCID000044

 [126 rows x 15 columns],
     year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0   1901  13.6   3.9   8.7  14.0  11.7   8.4  21.2   9.4  13.1  19.4  11.1
 1   1902   9.6  10.1  19.6  67.4  10.0  23.1  11.4  15.9  32.3   9.4   0.2
 2   1903  10.2  15.1   4.7  10.6  14.3  13.8  17.9  12.9  19.3  13.2  13.8
 3   1904  12.4   6.5   9.3   6.8  41.4  10.8  21.4   9.8  16.1  12.8  11.5
 4   1905   7.6   7.2   6.1  12.6  11.6  12.8  14.9  18.4  32.4  12.4  21.5
 ..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 94  1995   7.5  12.1  11.7  11.5  12.9  17.0  12.1  27.4  16.0   2.2  13.0
 95  1996   0.7   8.4   8.5   3.8  50.3  18.6  20.5  37.1   9.6  17.1   7.0
 96  1997   2.0  22.4   7.9   9.8  10.2  13.6  35.2  17.6   3.7   9.1   7.5
 97  1998   8.1   4.3  10.1   5.7  13.3  13.5  10.6  12.7  10.8  19.4  15.1
 98  1999  10.8  13.0   9.6   6.3   9.1  17.4  19.6  12.1   3.3   4.8   6.3

      dec  annual      Station
 0    9.4    21.2  61700003319
 1    7.7    67.4  61700003319
 2    5.5    19.3  61700003319

In [2]:
for i, df in enumerate(dataframes, start=1):
    print(f"Shape of csv{i}:", df.shape)

Shape of csv1: (99, 15)
Shape of csv2: (126, 15)
Shape of csv3: (126, 15)
Shape of csv4: (135, 15)
Shape of csv5: (126, 15)
Shape of csv6: (135, 15)
Shape of csv7: (51, 15)
Shape of csv8: (126, 15)
Shape of csv9: (126, 15)
Shape of csv10: (126, 15)
Shape of csv11: (126, 15)
Shape of csv12: (99, 15)
Shape of csv13: (126, 15)
Shape of csv14: (126, 15)
Shape of csv15: (129, 15)
Shape of csv16: (126, 15)
Shape of csv17: (83, 15)
Shape of csv18: (99, 15)
Shape of csv19: (99, 15)
Shape of csv20: (93, 15)
Shape of csv21: (99, 15)
Shape of csv22: (91, 15)
Shape of csv23: (129, 15)
Shape of csv24: (126, 15)
Shape of csv25: (99, 15)
Shape of csv26: (99, 15)
Shape of csv27: (90, 15)
Shape of csv28: (99, 15)
Shape of csv29: (99, 15)
Shape of csv30: (99, 15)
Shape of csv31: (126, 15)
Shape of csv32: (126, 15)
Shape of csv33: (99, 15)
Shape of csv34: (121, 15)
Shape of csv35: (126, 15)
Shape of csv36: (126, 15)
Shape of csv37: (99, 15)
Shape of csv38: (109, 15)

In [3]:
print(type(dataframes))

<class 'list'>

In [4]:
import pandas as pd

def merge_csv_files(file_paths):
    dfs = []

    for file_path in file_paths:
        df = pd.read_csv(file_path)
        dfs.append(df)

    merged_df_RX1day = pd.concat(dfs, ignore_index=True)

    return merged_df_RX1day

merged_df_RX1day = pd.concat(dataframes, ignore_index=True)
merged_df_RX1day

,year,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,annual,Station
0,1901,23.1,8.2,11.2,6.4,11.7,31.4,41.9,51.7,16.9,22.3,7.7,8.2,51.7,61700004063
1,1902,6.5,8.6,8.7,6.1,13.2,17.0,13.6,14.9,8.2,21.8,4.9,20.6,21.8,61700004063
2,1903,24.2,2.5,4.7,6.6,11.6,11.7,15.2,14.8,9.5,20.6,9.7,5.0,24.2,61700004063
3,1904,8.3,16.1,15.9,7.8,17.0,18.1,10.1,14.2,18.6,16.6,17.5,9.0,18.6,61700004063
4,1905,14.4,5.1,18.1,9.3,5.4,26.4,24.1,13.1,9.8,8.6,17.6,7.8,26.4,61700004063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4239,1995,19.0,17.0,18.0,11.0,15.0,11.0,18.0,44.0,26.0,7.0,7.0,15.0,44.0,61700010147
4240,1996,1.0,13.0,3.0,12.0,14.0,9.0,27.0,28.0,8.0,17.0,14.0,10.0,28.0,61700010147
4241,1997,3.0,15.0,13.0,10.0,19.0,20.0,27.0,54.0,17.0,11.0,14.0,10.0,54.0,61700010147
4242,1998,24.0,5.0,21.0,11.0,5.0,41.0,12.0,25.0,21.0,33.0,12.0,16.0,41.0,61700010147
4243,1999,15.0,10.0,11.0,11.0,10.0,11.0,7.0,11.0,11.0,4.0,9.6,26.7,26.7,61700010147

In [5]:
merged_df_RX1day.head(30)

,year,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,annual,Station
0,1901,23.1,8.2,11.2,6.4,11.7,31.4,41.9,51.7,16.9,22.3,7.7,8.2,51.7,61700004063
1,1902,6.5,8.6,8.7,6.1,13.2,17.0,13.6,14.9,8.2,21.8,4.9,20.6,21.8,61700004063
2,1903,24.2,2.5,4.7,6.6,11.6,11.7,15.2,14.8,9.5,20.6,9.7,5.0,24.2,61700004063
3,1904,8.3,16.1,15.9,7.8,17.0,18.1,10.1,14.2,18.6,16.6,17.5,9.0,18.6,61700004063
4,1905,14.4,5.1,18.1,9.3,5.4,26.4,24.1,13.1,9.8,8.6,17.6,7.8,26.4,61700004063
5,1906,10.1,10.0,21.6,14.1,18.0,14.0,47.8,19.5,21.6,15.5,11.4,8.5,47.8,61700004063
6,1907,6.4,9.6,19.4,6.1,11.9,18.0,18.0,14.5,20.5,11.1,6.6,16.0,20.5,61700004063
7,1908,3.4,9.3,5.4,7.3,11.0,74.5,19.1,18.7,9.7,2.5,8.9,5.5,74.5,61700004063
8,1909,10.1,14.5,5.0,7.3,17.6,16.7,18.6,15.4,32.3,8.4,14.1,13.2,32.3,61700004063
9,1910,13.0,10.4,9.1,13.0,8.4,44.8,21.0,38.0,10.6,4.5,16.5,11.3,44.8,61700004063
10,1911,9.7,8.7,7.4,8.7,15.6,8.2,6.0,4.1,12.6,7.2,13.0,10.3,15.6,61700004063
11,1912,13.6,9.6,11.1,3.1,17.0,11.8,16.7,13.4,13.7,5.7,9.9,15.4,17.0,61700004063
12,1913,9.4,10.1,8.1,10.2,12.4,31.6,8.8,15.5,13.4,28.8,20.9,11.4,31.6,61700004063
13,1914,5.9,9.1,15.2,7.7,20.8,21.1,20.7,39.7,15.6,9.3,16.9,10.1,39.7,61700004063
14,1915,17.1,9.7,16.4,13.1,16.3,8.9,16.6,12.4,8.0,18.6,17.2,10.8,18.6,61700004063
15,1916,8.4,18.6,-99.9,-99.9,11.6,16.0,12.8,16.8,27.8,16.4,9.8,10.0,-99.9,61700004063
16,1917,7.4,1.0,17.8,11.7,16.1,24.7,18.8,24.7,5.9,9.3,11.0,8.8,24.7,61700004063
17,1918,17.6,5.3,7.3,15.1,11.4,9.8,18.0,14.0,9.6,8.7,9.8,14.0,18.0,61700004063
18,1919,6.1,7.3,8.0,20.2,7.6,6.0,28.2,20.4,12.0,11.1,16.5,10.8,28.2,61700004063
19,1920,24.7,9.7,9.0,8.9,18.0,4.6,18.6,28.9,16.2,5.1,7.5,8.1,28.9,61700004063
20,1921,9.6,2.8,3.1,11.6,17.8,7.4,16.1,19.2,8.0,12.7,6.0,9.3,19.2,61700004063
21,1922,12.9,12.7,10.4,13.4,24.0,26.8,9.6,25.6,28.5,17.6,11.6,14.7,28.5,61700004063
22,1923,14.6,9.2,5.2,15.7,14.1,7.8,15.8,14.4,9.9,30.4,11.8,9.4,30.4,61700004063
23,1924,4.6,6.0,12.0,10.0,18.3,15.4,7.1,19.4,16.5,7.8,33.4,10.8,33.4,61700004063
24,1925,5.6,5.0,6.8,12.0,20.7,7.5,21.0,17.0,9.7,8.5,7.0,19.1,21.0,61700004063
25,1926,10.0,11.5,10.4,4.2,16.7,20.4,38.0,13.0,4.0,12.3,6.3,4.2,38.0,61700004063
26,1927,6.5,6.4,7.0,24.4,6.8,55.7,15.7,13.6,53.9,18.2,39.8,10.0,55.7,61700004063
27,1928,12.5,11.9,4.0,14.7,9.3,8.5,7.8,27.0,13.1,15.3,14.3,14.0,27.0,61700004063
28,1929,5.6,11.2,2.4,8.0,12.5,10.0,12.5,10.0,9.8,17.9,6.7,9.3,17.9,61700004063
29,1930,8.0,6.8,11.2,19.8,10.8,9.6,19.0,22.2,12.9,33.4,19.2,9.1,33.4,61700004063

In [6]:
merged_df_RX1day.to_csv('RX1day.csv', index=False)