In [1]:
import os
import pandas as pd

def read_csv_files(directory):
    data_frames = []
    
    for filename in os.listdir(directory):
        if filename.endswith(".csv"):
            file_path = os.path.join(directory, filename)
            original_df = pd.read_csv(file_path)
            
            if len(original_df.columns) == 1:
                first_column_name = original_df.columns[0]
                column_names = first_column_name.split()

                split_columns = original_df.iloc[:, 0].str.split(expand=True)
                new_df = pd.concat([original_df, split_columns], axis=1)
                new_df = new_df.drop(new_df.columns[0], axis=1)
                new_df.columns = column_names
                original_df = new_df
            
            original_df['Station'] = filename.split('.')[0]
            data_frames.append(original_df)
            
    return data_frames

csv_directory = '/Users/roshanchandru/Desktop/Dissertation/Dataset/Germany/Indicies/TNx'

dataframes = read_csv_files(csv_directory)
dataframes

[    year  jan  feb  mar   apr   may   jun   jul   aug   sep   oct  nov  dec  \
 0   1901  1.5  2.4  3.8   8.7  13.6  16.6  17.0  17.7  13.4  12.0  6.1  5.1
 1   1902  4.8  1.5  6.8  10.1  13.8  16.1  18.1  16.1  14.4  11.2  4.7  3.8
 2   1903  4.5  7.8  7.2   7.1  11.1  14.8  17.3  15.6  14.9  14.0  8.2  1.6
 3   1904  4.0  3.9  4.2  12.1  15.1  14.5  16.6  15.8  12.9  11.3  6.7  6.1
 4   1905  1.0  3.1  8.3   9.9  12.3  14.9  20.2  16.3  14.7   6.1  5.1  4.0
 ..   ...  ...  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...  ...
 94  1995  6.0  6.4  6.2  11.6  13.7  15.8  17.8  16.6  13.3  13.3  7.7  5.1
 95  1996  1.2  1.4  5.0  10.5  12.7  17.9  15.4  16.6  13.1  12.0  8.3  2.9
 96  1997  0.6  7.8  8.7   9.7  14.8  17.2  15.4  17.1  17.5  15.3  6.0  9.0
 97  1998  8.8  5.7  9.6  11.7  14.3  17.5  16.9  17.4  16.6  11.3  8.6  5.2
 98  1999  7.0  1.7  7.8   8.2  13.6  16.4  18.8  17.2  15.4  13.1  9.7  6.0

     annual      Station
 0     17.7  61700004063
 1     18.1  61700004063
 2     17.3  61700004063
 3     16.6  61700004063
 4     20.2  61700004063
 ..     ...          ...
 94    17.8  61700004063
 95    17.9  61700004063
 96    17.5  61700004063
 97    17.5  61700004063
 98    18.8  61700004063

 [99 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000   6.2   6.4   7.9  16.2  12.0  19.7  16.0  17.6  14.8  11.4   8.6
 122  2001   4.2   7.1   9.6  10.5  13.6  14.2  18.7  18.8  12.9  13.9  10.4
 123  2002   8.0  10.3   6.8  10.9  13.9  18.3  18.1  18.7  16.4  10.4   7.7
 124  2003   5.5   1.3   7.8  13.1  13.9  17.5  18.9  19.1  15.2  10.5  11.5
 125  2004   4.0  11.1  10.2   9.9  13.2  16.1  17.1  19.1  15.4  13.8   9.0

       dec  annual      Station
 0   -99.9   -99.9  LOCID000043
 1   -99.9   -99.9  LOCID000043
 2   -99.9   -99.9  LOCID000043
 3   -99.9   -99.9  LOCID000043
 4   -99.9   -99.9  LOCID000043
 ..    ...     ...          ...
 121  10.2    19.7  LOCID000043
 122   5.2    18.8  LOCID000043
 123   5.8    18.7  LOCID000043
 124   5.6    19.1  LOCID000043
 125   7.0    19.1  LOCID000043

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 122  2001 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 123  2002 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 124  2003 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 125  2004 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9

       dec  annual      Station
 0   -99.9   -99.9  LOCID000042
 1   -99.9   -99.9  LOCID000042
 2   -99.9   -99.9  LOCID000042
 3   -99.9   -99.9  LOCID000042
 4   -99.9   -99.9  LOCID000042
 ..    ...     ...          ...
 121 -99.9   -99.9  LOCID000042
 122 -99.9   -99.9  LOCID000042
 123 -99.9   -99.9  LOCID000042
 124 -99.9   -99.9  LOCID000042
 125 -99.9   -99.9  LOCID000042

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1870   6.2   2.5   4.3  11.0  15.8  17.5  21.2  18.5  13.8  10.0   8.7
 1    1871   0.0   3.7   6.6  10.0  13.2  15.0  17.8  19.3  17.0   7.1   3.1
 2    1872   2.7   7.5   9.5  12.5  14.5  15.0  20.5  15.5  17.0  11.2   9.7
 3    1873   6.2   4.5   8.0  11.3  11.6  17.5  19.2  19.3  15.3  14.7   7.1
 4    1874   8.2   2.8   8.3  12.5  14.7  17.8  20.8  18.1  17.8  13.5   6.0
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 130  2000   9.0   8.1  10.5  13.8  17.6  18.9  16.6  19.3  16.6  13.7   9.1
 131  2001   7.3   9.6   9.2  11.9  18.3  18.2  20.4  20.0  14.4  18.5   7.6
 132  2002  11.2 -99.9  12.6  12.2  14.8  20.3  18.6  18.9  16.3  12.9  10.4
 133  2003   7.6   2.6  10.6  13.9  16.7  18.7  18.5  23.5  15.0  12.9   9.7
 134  2004   4.9   9.3  10.9  12.3  13.3  17.7  19.8  19.0  17.0  13.3  10.2

      dec  annual      Station
 0    6.2    21.2  LOCID000040
 1    1.8    19.3  LOCID000040
 2    5.5    20.5  LOCID000040
 3    6.2    19.3  LOCID000040
 4    4.3    20.8  LOCID000040
 ..   ...     ...          ...
 130  9.8    19.3  LOCID000040
 131  9.2    20.4  LOCID000040
 132  7.2    20.3  LOCID000040
 133  7.0    23.5  LOCID000040
 134  7.2    19.8  LOCID000040

 [135 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 122  2001 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 123  2002 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 124  2003 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 125  2004 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9

       dec  annual      Station
 0   -99.9   -99.9  LOCID000054
 1   -99.9   -99.9  LOCID000054
 2   -99.9   -99.9  LOCID000054
 3   -99.9   -99.9  LOCID000054
 4   -99.9   -99.9  LOCID000054
 ..    ...     ...          ...
 121 -99.9   -99.9  LOCID000054
 122 -99.9   -99.9  LOCID000054
 123 -99.9   -99.9  LOCID000054
 124 -99.9   -99.9  LOCID000054
 125 -99.9   -99.9  LOCID000054

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1870 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1871 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1872 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1873 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1874 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 130  2000   4.3   6.4   9.2  15.0  14.8  18.2  15.8  18.0  16.3  13.2   7.1
 131  2001   5.8   8.2   9.0   8.7  16.6  17.2  18.1  19.9  14.3  16.1   7.4
 132  2002   7.2   9.7   9.0   9.7  13.8  18.0  18.6  18.5  14.3  11.4   7.7
 133  2003   3.7  -0.5   9.1  12.8  14.5  18.5  19.3  21.1  13.5  11.9   9.5
 134  2004   2.9  11.2   9.7   9.3  11.8  17.6  17.5  18.9  14.3  15.3  11.2

       dec  annual      Station
 0   -99.9   -99.9  LOCID000041
 1   -99.9   -99.9  LOCID000041
 2   -99.9   -99.9  LOCID000041
 3   -99.9   -99.9  LOCID000041
 4   -99.9   -99.9  LOCID000041
 ..    ...     ...          ...
 130   9.4    18.2  LOCID000041
 131   4.7    19.9  LOCID000041
 132   4.7    18.6  LOCID000041
 133   6.2    21.1  LOCID000041
 134   4.9    18.9  LOCID000041

 [135 rows x 15 columns],
     year  jan  feb  mar   apr   may   jun   jul   aug   sep   oct   nov   dec  \
 0   1912  5.3  6.3  8.3   8.4  10.9  16.4  18.2  15.6  11.1  10.9   5.9   7.2
 1   1913  2.2  6.4  7.8  13.5  15.7  14.3  15.8  16.4  14.9  11.4   9.9   5.6
 2   1914  4.0  7.2  6.1   9.1  13.9  15.0  18.4  16.2  15.4  10.3   8.8   8.6
 3   1915  3.6  2.1  5.7   5.5  11.3  18.0  15.8  14.8  13.1  11.0   6.6   5.9
 4   1916  6.2  2.8  5.4   8.7  14.2  14.7  16.1  14.6  12.9  12.9   8.7   6.6
 5   1917  5.3  2.2  2.1   3.9  15.5  18.1  16.7  16.9  14.5  12.1   9.7   4.4
 6   1918  4.8  6.9  5.5   8.4  14.7  12.3  15.9  16.5  14.9  10.5   8.8   6.8
 7   1919  3.3  5.0  7.4   8.6  11.9  15.2  14.9  16.7  16.1  13.1   3.2   3.8
 8   1920  6.5  5.1  7.8  10.5  15.3  15.7  17.4  14.5  13.0  14.1   8.2   7.0
 9   1921  9.3  5.3  7.5  10.1  15.3  15.5  17.6  18.0  13.7  12.9   4.2   6.8
 10  1922  4.0  4.9  7.5  12.2  17.7  14.0  17.2  15.3  12.6   7.8   6.2   5.7
 11  1923  5.4  5.9  6.5   9.5  12.2  14.5  20.2  14.2  14.7  12.2   7.1   4.7
 12  1924  2.7  3.4  7.1   7.8  15.5  15.6  17.4  16.4  14.3  10.3   8.0   6.2
 13  1925  7.8  5.6  4.9   6.4  12.7  13.9  18.7  20.1  12.6  12.0   8.5   8.6
 14  1926  4.1  7.3  7.6   9.5  12.9  14.9  18.5  15.3  15.1  11.8   9.8   7.5
 15  1927  6.2  5.8  8.5   8.2  10.1  13.5  16.9  17.6  15.1  13.2  13.0   2.2
 16  1928  3.9  8.9  6.1  12.9  13.3  14.6  18.5  15.4  13.8  10.9  10.7   2.7
 17  1929  1.1 -1.3  5.8  10.3  13.5  16.5  19.1  16.9  15.9  10.4   8.6   8.6
 18  1930  7.6  0.6  4.1   9.7  12.0  17.7  18.0  15.7  13.2  10.7   8.7   5.4
 19  1931  2.8  2.6  4.3   6.8  17.4  14.7  17.2  16.8  13.9  13.6  10.9   4.9
 20  1932  6.6  3.8  6.4  11.6  15.5  15.1  18.7  19.2  17.1  12.5   9.4   4.5
 21  1933  7.2  7.1  8.9   9.7  13.9  14.5  17.5  15.8  11.7  11.9   5.6   2.4
 22  1934  7.2  3.7  5.9  10.9  14.7  15.7  16.6  16.8  15.5  12.7   8.1   9.7
 23  1935  5.8  6.3  8.0  10.0  10.7  18.6  16.7  16.3  15.5  12.2   9.5   4.7
 24  1936  6.4  4.5  8.2   9.2  10.5  16.9  17.4  15.9  13.9  10.9   7.4   6.4
 25  1937  7.4  5.6  4.6   8.9  16.4  19.0  17.1  17.8  15.4  12.9   8.4   5.6
 26  1938  6.7  5.6  9.0   7.0  12.7  16.0  16.9  19.3  15.1  13.3  10.7   4.9
 27  1939  6.6  7.9  3.8  10.5  12.0  16.8  16.9  18.2  15.1   9.3  10.0   7.6
 28  1940  0.3  3.9  8.0  11.1  15.0  15.8  15.8  14.8  12.3  12.1   9.1   1.8
 29  1941 -1.4  3.6  5.2   7.4  11.6  18.0  22.3  16.3  12.6  10.9   4.6   8.2
 30  1942  2.9 -1.0  3.9   7.9  12.2  12.4  16.4  19.4  18.2  12.0   8.3   7.4
 31  1943  3.8  6.2  6.8  10.4  13.4  14.1  18.0  18.2  17.4  11.8   5.7   5.2
 32  1944  6.3  5.5  2.8  10.0  14.3  15.6  17.8  20.0  14.0   9.8   9.6   6.2
 33  1945  0.6  7.6  8.1   7.7  16.2  17.0  16.8  16.8  15.3  11.9  10.3   5.2
 34  1946  4.1  5.2  6.7   9.8  15.5  13.9  18.8  15.6  13.3   8.1   6.6   3.0
 35  1947  2.9 -5.3  7.2   9.3  14.9  21.5  18.3  16.2  17.2  10.8  13.0   5.5
 36  1948  6.5  6.2  7.7  12.6  14.5  15.0  18.2  20.0  15.0  10.6   9.8   5.2
 37  1949  5.6  7.5  3.7  10.4  12.2  16.4  16.8  17.8  18.2  12.5   6.2   5.3
 38  1950  5.2  8.7  7.5   6.8  17.0  17.0  17.0  19.4  13.5  11.1   6.6   6.5
 39  1951  3.3  3.5  7.3   8.9   9.7  15.6  16.9  17.2  17.2  11.5   7.6   7.8
 40  1952  4.2  5.0  5.0  11.0  12.1  13.8  16.3  17.0  13.1   9.9   6.3   1.1
 41  1953  6.5  5.6  8.0   9.1  16.0  17.2  18.2  17.0  12.7  13.8   9.3   8.2
 42  1954  4.9  1.5  4.5   6.3  14.3  17.8  15.8  16.5  16.2  13.6   6.4   7.8
 43  1955  2.6  2.7  7.0  13.9  11.1  16.4  17.0  16.5  15.5  11.2   9.6   8.0
 44  1956  3.0  1.0  4.0   5.4  13.9  13.0  16.8  13.2  13.0  12.4   7.5   8.5
 45  1957  6.5  5.5  8.7   7.5  11.0  17.5  18.6  16.0  12.9  11.5   8.6   4.4
 46  1958  3.5  6.5  2.2   6.3  14.0  15.4  16.1  16.2  14.9  13.9   7.0   5.5
 47  1959  6.0  5.5  7.9  12.0  11.9  14.9  19.5  17.9  12.9   9.4   5.2   4.0
 48  1960  6.4  8.0  6.4   7.0  12.7  15.3  16.5  17.2  13.8  11.2   8.8   7.3
 49  1961  3.8  5.5  8.1  10.7  11.9  14.4  15.2  15.0  15.9  12.0   6.9   5.6
 50  1962  5.8  4.4  4.0   9.8  11.9  16.0  15.6  13.6  15.0 -99.9 -99.9 -99.9

     annual      Station
 0     18.2  61700003865
 1     16.4  61700003865
 2     18.4  61700003865
 3     18.0  61700003865
 4     16.1  61700003865
 5     18.1  61700003865
 6     16.5  61700003865
 7     16.7  61700003865
 8     17.4  61700003865
 9     18.0  61700003865
 10    17.7  61700003865
 11    20.2  61700003865
 12    17.4  61700003865
 13    20.1  61700003865
 14    18.5  61700003865
 15    17.6  61700003865
 16    18.5  61700003865
 17    19.1  61700003865
 18    18.0  61700003865
 19    17.4  61700003865
 20    19.2  61700003865
 21    17.5  61700003865
 22    16.8  61700003865
 23    18.6  61700003865
 24    17.4  61700003865
 25    19.0  61700003865
 26    19.3  61700003865
 27    18.2  61700003865
 28    15.8  61700003865
 29    22.3  61700003865
 30    19.4  61700003865
 31    18.2  61700003865
 32    20.0  61700003865
 33    17.0  61700003865
 34    18.8  61700003865
 35    21.5  61700003865
 36    20.0  61700003865
 37    18.2  61700003865
 38    19.4  61700003865
 39    17.2  61700003865
 40    17.0  61700003865
 41    18.2  61700003865
 42    17.8  61700003865
 43    17.0  61700003865
 44    16.8  61700003865
 45    18.6  61700003865
 46    16.2  61700003865
 47    19.5  61700003865
 48    17.2  61700003865
 49    15.9  61700003865
 50   -99.9  61700003865  ,
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000   5.6   7.5  10.7  13.0  14.8  17.8  15.7  17.4  17.3  13.4   9.0
 122  2001   7.0   9.2   9.0  10.3  17.3  17.6  17.5  19.2  14.8  14.4   7.7
 123  2002 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 124  2003 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 125  2004 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9

       dec  annual      Station
 0   -99.9   -99.9  LOCID000045
 1   -99.9   -99.9  LOCID000045
 2   -99.9   -99.9  LOCID000045
 3   -99.9   -99.9  LOCID000045
 4   -99.9   -99.9  LOCID000045
 ..    ...     ...          ...
 121  10.4    17.8  LOCID000045
 122   6.1    19.2  LOCID000045
 123 -99.9   -99.9  LOCID000045
 124 -99.9   -99.9  LOCID000045
 125 -99.9   -99.9  LOCID000045

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 122  2001 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 123  2002 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 124  2003 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 125  2004 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9

       dec  annual      Station
 0   -99.9   -99.9  LOCID000051
 1   -99.9   -99.9  LOCID000051
 2   -99.9   -99.9  LOCID000051
 3   -99.9   -99.9  LOCID000051
 4   -99.9   -99.9  LOCID000051
 ..    ...     ...          ...
 121 -99.9   -99.9  LOCID000051
 122 -99.9   -99.9  LOCID000051
 123 -99.9   -99.9  LOCID000051
 124 -99.9   -99.9  LOCID000051
 125 -99.9   -99.9  LOCID000051

 [126 rows x 15 columns],
      year  jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879  4.2   7.2   6.2   9.0  16.8  18.0  17.2  19.2  15.8  13.0   6.8
 1    1880  5.2   6.6   7.6  12.8  15.6  18.4  19.0  18.6  18.8  13.8  10.2
 2    1881  2.4   2.2   6.8   7.4  16.6  18.0  22.3  18.0  15.2   8.4  10.8
 3    1882  4.0   7.4   8.0   9.6  16.0  17.0  19.2  21.0  14.8  10.0   8.0
 4    1883  3.9   4.2  -0.4   5.5  15.6  15.8  18.0  16.0  14.0  11.0   5.2
 ..    ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000  4.3   5.5   8.3  14.7  15.2  20.8  16.0  17.5  15.0  12.5   7.7
 122  2001  3.9   8.0   8.6  10.1  14.7  16.5  18.0  19.7  14.3  12.6   8.2
 123  2002  8.6   8.8   7.6  11.1  15.8  20.5  20.2  20.3  16.1  12.0   8.4
 124  2003  4.0  -0.5   7.1  13.0  15.8  19.8  20.4  21.2  14.7  10.7   9.0
 125  2004  4.2  12.1  10.8  10.0  13.8  17.3  18.3  19.7  15.3  14.4   9.9

      dec  annual      Station
 0    2.0    19.2  LOCID000050
 1    6.8    19.0  LOCID000050
 2    3.0    22.3  LOCID000050
 3    6.0    21.0  LOCID000050
 4    5.0    18.0  LOCID000050
 ..   ...     ...          ...
 121  8.6    20.8  LOCID000050
 122  4.1    19.7  LOCID000050
 123  3.6    20.5  LOCID000050
 124  5.9    21.2  LOCID000050
 125  5.9    19.7  LOCID000050

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 122  2001 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 123  2002 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 124  2003 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 125  2004 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9

       dec  annual      Station
 0   -99.9   -99.9  LOCID000044
 1   -99.9   -99.9  LOCID000044
 2   -99.9   -99.9  LOCID000044
 3   -99.9   -99.9  LOCID000044
 4   -99.9   -99.9  LOCID000044
 ..    ...     ...          ...
 121 -99.9   -99.9  LOCID000044
 122 -99.9   -99.9  LOCID000044
 123 -99.9   -99.9  LOCID000044
 124 -99.9   -99.9  LOCID000044
 125 -99.9   -99.9  LOCID000044

 [126 rows x 15 columns],
     year  jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0   1901  3.0   3.0   5.1  10.6  16.8  20.1  19.7  19.6  14.8  14.6   7.2
 1   1902  6.4   0.6   8.4   7.0  17.1  19.2  18.5  15.6  16.5   9.7   6.2
 2   1903  6.6   7.6   9.9  11.7  16.9  17.9  17.7  17.8  17.8  13.3   8.7
 3   1904  4.6   3.1   5.7  13.2  16.2  19.3  20.7  19.5  14.8  13.4   9.8
 4   1905  4.1   6.4   6.9  10.8  16.5  19.9  23.8  19.5  16.1   8.1   7.5
 ..   ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 94  1995  5.0   5.2   6.5  14.7  16.3  14.9  20.5  18.0  14.6  14.0   6.0
 95  1996  0.2   0.3   3.8  12.9  13.8  17.6  15.7  17.6  11.8  11.3  12.4
 96  1997  2.2   7.2   8.4  10.0  15.3  18.3  17.9  19.2  17.5  16.5   7.1
 97  1998  7.2  10.0  10.1  12.9  16.9  19.2  18.9  16.8  15.6  10.8   5.2
 98  1999  9.8   5.4   6.2  11.9  16.2  15.1  19.6  16.1  16.8  12.3  10.2

     dec  annual      Station
 0   5.0    20.1  61700003319
 1   5.6    19.2  61700003319
 2   1.6    17.9  61700003319
 3   8.4    20.7  61700003319
 4   5.8    23.8  61700003319
 ..  ...     ...          ...
 94  3.9    20.5  61700003319
 95  3.3    17.6  61700003319
 96  8.3    19.2  61700003319
 97  8.1    19.2  61700003319
 98  5.7    19.6  61700003319

 [99 rows x 15 columns],

In [2]:
for i, df in enumerate(dataframes, start=1):
    print(f"Shape of csv{i}:", df.shape)

Shape of csv1: (99, 15)
Shape of csv2: (126, 15)
Shape of csv3: (126, 15)
Shape of csv4: (135, 15)
Shape of csv5: (126, 15)
Shape of csv6: (135, 15)
Shape of csv7: (51, 15)
Shape of csv8: (126, 15)
Shape of csv9: (126, 15)
Shape of csv10: (126, 15)
Shape of csv11: (126, 15)
Shape of csv12: (99, 15)
Shape of csv13: (126, 15)
Shape of csv14: (126, 15)
Shape of csv15: (129, 15)
Shape of csv16: (126, 15)
Shape of csv17: (83, 15)
Shape of csv18: (99, 15)
Shape of csv19: (99, 15)
Shape of csv20: (93, 15)
Shape of csv21: (99, 15)
Shape of csv22: (91, 15)
Shape of csv23: (129, 15)
Shape of csv24: (126, 15)
Shape of csv25: (99, 15)
Shape of csv26: (99, 15)
Shape of csv27: (90, 15)
Shape of csv28: (99, 15)
Shape of csv29: (99, 15)
Shape of csv30: (99, 15)
Shape of csv31: (126, 15)
Shape of csv32: (126, 15)
Shape of csv33: (99, 15)
Shape of csv34: (121, 15)
Shape of csv35: (126, 15)
Shape of csv36: (126, 15)
Shape of csv37: (99, 15)
Shape of csv38: (109, 15)

In [3]:
print(type(dataframes))

<class 'list'>

In [4]:
import pandas as pd

def merge_csv_files(file_paths):
    dfs = []

    for file_path in file_paths:
        df = pd.read_csv(file_path)
        dfs.append(df)

    merged_df_TNx = pd.concat(dfs, ignore_index=True)

    return merged_df_TNx

merged_df_TNx = pd.concat(dataframes, ignore_index=True)
merged_df_TNx

,year,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,annual,Station
0,1901,1.5,2.4,3.8,8.7,13.6,16.6,17.0,17.7,13.4,12.0,6.1,5.1,17.7,61700004063
1,1902,4.8,1.5,6.8,10.1,13.8,16.1,18.1,16.1,14.4,11.2,4.7,3.8,18.1,61700004063
2,1903,4.5,7.8,7.2,7.1,11.1,14.8,17.3,15.6,14.9,14.0,8.2,1.6,17.3,61700004063
3,1904,4.0,3.9,4.2,12.1,15.1,14.5,16.6,15.8,12.9,11.3,6.7,6.1,16.6,61700004063
4,1905,1.0,3.1,8.3,9.9,12.3,14.9,20.2,16.3,14.7,6.1,5.1,4.0,20.2,61700004063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4239,1995,5.6,6.8,7.6,11.8,14.5,14.9,19.6,18.4,14.5,14.5,8.1,0.8,19.6,61700010147
4240,1996,0.3,4.1,2.6,13.6,14.0,18.0,15.0,17.6,12.5,11.3,13.4,4.6,18.0,61700010147
4241,1997,2.4,8.8,7.5,10.3,16.0,17.1,16.5,20.7,16.8,14.1,8.0,8.5,20.7,61700010147
4242,1998,9.6,9.5,9.8,10.5,13.1,17.0,19.8,16.9,15.9,12.7,5.3,7.4,19.8,61700010147
4243,1999,8.4,5.8,9.4,11.4,13.1,16.5,19.3,17.9,17.0,11.5,9.4,6.8,19.3,61700010147

In [5]:
merged_df_TNx.head(30)

,year,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,annual,Station
0,1901,1.5,2.4,3.8,8.7,13.6,16.6,17.0,17.7,13.4,12.0,6.1,5.1,17.7,61700004063
1,1902,4.8,1.5,6.8,10.1,13.8,16.1,18.1,16.1,14.4,11.2,4.7,3.8,18.1,61700004063
2,1903,4.5,7.8,7.2,7.1,11.1,14.8,17.3,15.6,14.9,14.0,8.2,1.6,17.3,61700004063
3,1904,4.0,3.9,4.2,12.1,15.1,14.5,16.6,15.8,12.9,11.3,6.7,6.1,16.6,61700004063
4,1905,1.0,3.1,8.3,9.9,12.3,14.9,20.2,16.3,14.7,6.1,5.1,4.0,20.2,61700004063
5,1906,4.3,5.0,8.1,9.0,13.1,17.9,16.8,16.5,15.0,11.8,8.5,2.2,17.9,61700004063
6,1907,2.3,1.8,2.8,9.8,12.8,15.1,16.0,18.5,13.9,12.4,6.0,4.6,18.5,61700004063
7,1908,2.7,4.1,3.6,5.8,13.8,16.2,15.9,15.1,12.4,8.1,3.6,2.3,16.2,61700004063
8,1909,2.0,3.0,4.6,11.0,12.5,14.0,15.2,17.0,12.6,14.2,7.9,6.8,17.0,61700004063
9,1910,5.5,5.5,3.1,10.4,15.0,15.1,16.6,15.2,12.3,13.4,6.3,4.9,16.6,61700004063
10,1911,1.7,4.4,10.4,8.8,14.1,14.7,20.3,17.4,14.9,10.9,7.1,4.8,20.3,61700004063
11,1912,4.3,8.0,9.8,8.1,13.9,15.3,15.3,15.1,9.6,10.3,2.7,7.3,15.3,61700004063
12,1913,3.5,5.5,7.2,9.9,14.9,15.8,14.8,13.3,13.9,10.5,8.9,5.9,15.8,61700004063
13,1914,1.4,4.2,7.3,9.6,12.4,14.1,16.9,17.4,13.6,8.9,7.9,8.2,17.4,61700004063
14,1915,5.1,1.9,6.3,8.0,12.7,17.6,16.6,15.6,14.8,10.0,5.1,8.2,17.6,61700004063
15,1916,6.1,1.6,5.7,8.3,14.0,13.5,15.0,15.4,13.5,12.5,8.2,4.9,15.4,61700004063
16,1917,7.0,0.9,2.9,6.4,14.1,15.4,16.9,15.0,14.8,13.3,7.7,0.7,16.9,61700004063
17,1918,5.2,6.4,5.9,9.2,13.5,15.0,18.5,17.6,14.9,9.1,7.6,7.8,18.5,61700004063
18,1919,2.8,4.1,8.5,7.1,8.4,16.1,15.4,15.4,14.3,10.0,7.9,6.7,16.1,61700004063
19,1920,6.8,3.9,7.5,10.9,15.1,14.5,16.9,13.0,11.3,12.6,8.3,8.1,16.9,61700004063
20,1921,8.0,2.6,5.7,8.3,14.5,16.0,19.7,15.5,15.7,11.3,6.5,4.4,19.7,61700004063
21,1922,3.8,5.3,6.4,10.9,16.4,14.0,18.3,15.2,11.9,10.5,5.0,4.4,18.3,61700004063
22,1923,2.3,6.4,6.8,9.4,12.8,15.1,16.7,15.5,12.3,12.9,7.8,4.3,16.7,61700004063
23,1924,1.6,1.9,8.8,10.4,14.5,13.9,16.9,15.9,15.2,9.8,8.5,4.5,16.9,61700004063
24,1925,6.5,5.0,2.3,7.8,13.2,14.2,16.4,19.1,14.7,12.0,9.8,10.6,19.1,61700004063
25,1926,2.8,7.0,9.3,11.7,13.0,15.1,17.1,15.5,15.7,11.5,7.6,3.3,17.1,61700004063
26,1927,4.7,4.9,5.2,10.1,14.0,15.0,16.7,17.2,13.7,9.1,11.3,4.5,17.2,61700004063
27,1928,3.8,7.1,7.2,8.8,13.1,14.4,18.7,16.7,14.0,10.6,8.4,3.0,18.7,61700004063
28,1929,-2.6,-0.7,5.8,7.1,14.0,14.3,18.6,15.1,16.1,15.8,7.4,7.4,18.6,61700004063
29,1930,2.9,0.9,6.1,11.0,14.0,17.2,18.2,16.7,15.3,12.2,10.0,1.8,18.2,61700004063

In [6]:
merged_df_TNx.to_csv('TNx.csv', index=False)