In [1]:
import os
import pandas as pd

def read_csv_files(directory):
    data_frames = []
    
    for filename in os.listdir(directory):
        if filename.endswith(".csv"):
            file_path = os.path.join(directory, filename)
            original_df = pd.read_csv(file_path)
            
            if len(original_df.columns) == 1:
                first_column_name = original_df.columns[0]
                column_names = first_column_name.split()

                split_columns = original_df.iloc[:, 0].str.split(expand=True)
                new_df = pd.concat([original_df, split_columns], axis=1)
                new_df = new_df.drop(new_df.columns[0], axis=1)
                new_df.columns = column_names
                original_df = new_df
            
            original_df['Station'] = filename.split('.')[0]
            data_frames.append(original_df)
            
    return data_frames

csv_directory = '/Users/roshanchandru/Desktop/Dissertation/Dataset/Germany/Indicies/TXn'

dataframes = read_csv_files(csv_directory)
dataframes

[    year   jan  feb  mar   apr   may   jun   jul   aug   sep   oct  nov   dec  \
 0   1901 -10.9 -5.6 -0.1   7.8  12.9  14.9  17.0  15.1  13.1   4.0 -1.6  -1.7
 1   1902  -0.5 -1.2  4.6  10.4   9.3  14.3  16.8  15.3  13.0   4.4 -2.0 -10.6
 2   1903  -5.6  2.3  5.0   6.0  13.0  16.7  16.0  16.0   9.3  10.3  1.3  -5.1
 3   1904  -4.5 -2.1  0.6   9.0  10.5  18.0  20.4  13.0  10.3   7.4 -0.1  -3.0
 4   1905  -9.5 -0.1  4.2   6.0  10.8  18.3  18.0  16.5  12.7   3.0  1.4  -2.8
 ..   ...   ...  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...   ...
 94  1995  -6.0  3.9  1.9   6.8  10.6  13.9  19.4  14.1   9.5  11.0 -0.6  -2.3
 95  1996  -3.9 -3.4 -1.9   1.8   8.5  14.4  13.8  17.4  10.4   9.3  0.9  -9.4
 96  1997  -6.6 -1.3  5.7   8.0  10.2  16.5  17.7  17.4  15.7   3.6  1.4  -1.3
 97  1998  -4.1 -4.3  3.9   6.9  11.7  14.3  15.7  14.4  10.0   7.6 -1.0  -4.2
 98  1999  -2.8 -3.4  3.0   7.5  14.3  14.9  17.0  19.2  16.0   9.6 -0.9  -2.5

     annual      Station
 0    -10.9  61700004063
 1    -10.6  61700004063
 2     -5.6  61700004063
 3     -4.5  61700004063
 4     -9.5  61700004063
 ..     ...          ...
 94    -6.0  61700004063
 95    -9.4  61700004063
 96    -6.6  61700004063
 97    -4.3  61700004063
 98    -3.4  61700004063

 [99 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000  -0.8   3.9   3.3   8.0  13.7  12.5  14.5  17.9  12.4  11.2   6.7
 122  2001  -2.0  -3.6   0.2   5.3  13.2  11.6  16.3  16.5  12.8   8.9   4.3
 123  2002  -2.0   3.0   3.4   6.3  10.9  16.8  16.1  20.2  12.7   3.6   2.7
 124  2003  -5.8  -1.9   4.2   1.3  10.1  16.0  17.9  16.3  13.2   2.3   4.1
 125  2004  -4.2   2.0   1.3   8.2  10.7  14.9  15.9  16.3  12.6   9.8   2.0

       dec  annual      Station
 0   -99.9   -99.9  LOCID000043
 1   -99.9   -99.9  LOCID000043
 2   -99.9   -99.9  LOCID000043
 3   -99.9   -99.9  LOCID000043
 4   -99.9   -99.9  LOCID000043
 ..    ...     ...          ...
 121  -2.6    -2.6  LOCID000043
 122  -2.3    -3.6  LOCID000043
 123  -3.8    -3.8  LOCID000043
 124   1.1    -5.8  LOCID000043
 125   1.3    -4.2  LOCID000043

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 122  2001 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 123  2002 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 124  2003 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 125  2004 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9

       dec  annual      Station
 0   -99.9   -99.9  LOCID000042
 1   -99.9   -99.9  LOCID000042
 2   -99.9   -99.9  LOCID000042
 3   -99.9   -99.9  LOCID000042
 4   -99.9   -99.9  LOCID000042
 ..    ...     ...          ...
 121 -99.9   -99.9  LOCID000042
 122 -99.9   -99.9  LOCID000042
 123 -99.9   -99.9  LOCID000042
 124 -99.9   -99.9  LOCID000042
 125 -99.9   -99.9  LOCID000042

 [126 rows x 15 columns],
      year   jan   feb  mar   apr   may   jun   jul   aug   sep   oct  nov  \
 0    1870  -3.1  -7.2  2.5   8.3  11.2  16.5  18.6  12.8  15.3   8.3  2.5
 1    1871 -11.0  -8.0  3.5   5.7  11.8   9.6  17.5  17.2  10.5   5.6  0.0
 2    1872  -2.5   0.0  4.5   7.0  12.5  16.6  18.9  18.3  11.7   8.7  0.8
 3    1873   0.5  -2.7  3.8   4.3  11.8  12.5  19.3  16.5  14.2   7.8  1.0
 4    1874  -1.7  -4.2  3.2  10.0  10.0  16.8  23.0  18.1  16.8   3.7 -0.2
 ..    ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   ...  ...
 130  2000  -0.6   3.0  6.1   8.8  13.4  17.8  15.3  21.5  15.8  11.5  7.1
 131  2001  -0.1   2.3  4.9   6.3  10.7  14.2  19.5  17.4  13.9  13.8  4.1
 132  2002  -6.6 -99.9  7.4  10.3  10.2  19.5  17.9  17.1  12.0   8.0  6.7
 133  2003  -5.2  -1.6  8.5   6.8  14.8  22.6  18.5  18.3  15.8   5.8  4.4
 134  2004  -1.5   2.8  1.2   9.2   9.3  16.7  17.9  18.1  14.3  10.6  3.3

       dec  annual      Station
 0   -11.7   -11.7  LOCID000040
 1   -10.0   -11.0  LOCID000040
 2     1.5    -2.5  LOCID000040
 3    -1.0    -2.7  LOCID000040
 4    -7.0    -7.0  LOCID000040
 ..    ...     ...          ...
 130  -3.1    -3.1  LOCID000040
 131  -2.5    -2.5  LOCID000040
 132  -2.4    -6.6  LOCID000040
 133   0.5    -5.2  LOCID000040
 134  -2.5    -2.5  LOCID000040

 [135 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 122  2001 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 123  2002 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 124  2003 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 125  2004 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9

       dec  annual      Station
 0   -99.9   -99.9  LOCID000054
 1   -99.9   -99.9  LOCID000054
 2   -99.9   -99.9  LOCID000054
 3   -99.9   -99.9  LOCID000054
 4   -99.9   -99.9  LOCID000054
 ..    ...     ...          ...
 121 -99.9   -99.9  LOCID000054
 122 -99.9   -99.9  LOCID000054
 123 -99.9   -99.9  LOCID000054
 124 -99.9   -99.9  LOCID000054
 125 -99.9   -99.9  LOCID000054

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1870 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1871 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1872 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1873 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1874 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 130  2000  -4.1   2.6   3.1   8.5  14.4  14.6  15.6  20.5  12.6  11.4   5.5
 131  2001  -2.7  -3.6   0.0   4.9   8.1  13.8  15.6  19.6  12.3   9.9   3.2
 132  2002  -4.3   1.3   2.2   5.1  11.7  15.5  15.4  19.9  10.5   4.6   3.2
 133  2003 -12.0  -4.4   3.5   2.6  13.7  19.5  19.3  17.7  11.6   3.4   3.3
 134  2004  -3.5   0.0  -0.2   6.8  10.6  14.8  15.5  18.2  12.1  10.2   2.6

       dec  annual      Station
 0   -99.9   -99.9  LOCID000041
 1   -99.9   -99.9  LOCID000041
 2   -99.9   -99.9  LOCID000041
 3   -99.9   -99.9  LOCID000041
 4   -99.9   -99.9  LOCID000041
 ..    ...     ...          ...
 130  -2.0    -4.1  LOCID000041
 131  -7.1    -7.1  LOCID000041
 132  -7.1    -7.1  LOCID000041
 133  -1.1   -12.0  LOCID000041
 134  -0.8    -3.5  LOCID000041

 [135 rows x 15 columns],
     year   jan   feb  mar  apr   may   jun   jul   aug   sep   oct   nov  \
 0   1912  -8.3 -11.0  5.7  2.3  10.0  13.4  15.6  14.6  10.5   3.0   2.6
 1   1913  -4.2   0.5  2.9  2.6  10.2  12.5  15.5  15.2  15.6   8.1   3.0
 2   1914  -3.3   1.6  3.6  8.5   9.3  11.4  17.1  19.7  12.4   4.8   0.1
 3   1915  -1.9  -4.6 -2.8  7.2   8.8  16.0  15.2  14.8  10.2   3.6  -3.2
 4   1916  -1.8  -2.4 -1.0  6.4  10.8  12.6  14.6  15.8  11.2   7.0  -2.2
 5   1917  -5.1  -8.4 -3.9  5.6  13.6  18.2  16.2  17.5  14.8   4.2   3.7
 6   1918  -3.0  -1.6  0.9  6.4   7.6  10.8  15.8  13.6  12.5   6.9   1.7
 7   1919  -5.4  -5.7  1.4  5.9   8.7  11.8  15.0  16.5   9.4   2.9  -6.3
 8   1920  -2.2  -0.4  6.0  8.2  11.0  14.8  15.8  14.4  13.8   3.4  -1.6
 9   1921  -0.6  -0.2  6.3  8.4  11.2  11.6  14.8  16.7  14.1   5.8  -3.4
 10  1922  -9.2 -10.6  1.8  2.3   8.9  16.8  15.2  15.4  13.5   0.7   0.4
 11  1923   0.7  -4.2  2.2  6.1   9.8   9.2  15.2  14.3  12.2   9.8  -0.2
 12  1924  -6.7  -3.7  0.6  3.8  10.3  12.4  17.9  16.5  14.1   5.8  -0.6
 13  1925  -0.7  -0.5 -2.1  7.4  10.7  13.4  17.4  16.0  12.4   5.6  -4.3
 14  1926  -5.2  -2.4  2.2  7.8   8.6  15.8  15.4  18.0  14.8   2.6   1.8
 15  1927  -1.1  -0.7  4.5  6.6   7.8  11.3  15.4  14.7  11.5   7.6  -3.8
 16  1928  -4.2  -0.4 -1.4  4.4   8.1  12.9  16.8  15.1  11.2   8.2   5.3
 17  1929  -8.4 -12.4 -0.3  2.0   9.6  12.4  14.8  17.8  14.2   8.0   3.4
 18  1930   0.8   0.2  0.4  4.9  10.2  17.6  16.8  13.8  13.8   5.7   0.7
 19  1931  -1.5  -3.4 -2.0  6.4  11.5  13.0  14.8  15.3  12.3   4.2  -1.8
 20  1932  -2.6  -2.9 -1.9  5.7   8.5  14.7  19.2  18.2  14.3   4.9   1.1
 21  1933  -7.3  -2.8  2.4  5.5  11.8  16.4  18.3  18.0  12.8   5.9  -0.1
 22  1934  -2.8  -0.5  3.6  8.6  10.8  16.8  16.3  15.5  13.2   7.6   2.8
 23  1935  -5.0  -0.7  0.4  4.8   7.1  15.4  16.0  16.0  12.8   5.4   2.6
 24  1936   1.1  -2.9  1.7  5.6  11.2  14.8  19.4  16.6  10.4   7.8  -1.0
 25  1937  -8.3  -3.7 -0.6  5.4  11.4  13.1  14.6  16.8  13.6  10.9  -1.8
 26  1938  -2.5   0.6  7.2  6.5   9.3  14.7  17.4  17.2  13.8   4.0   6.6
 27  1939  -4.6  -1.2  1.4  7.4  11.4  17.0  17.0  19.1  11.8   5.4   0.2
 28  1940 -12.0 -13.0  0.0  2.4  10.6  17.6  15.1  13.4  11.2   4.7   1.8
 29  1941 -12.3  -9.6  1.0  4.4   7.4  14.4  18.0  15.3  13.3   3.9  -0.9
 30  1942 -14.2  -7.6 -5.9  5.4   7.0  13.0  15.2  18.1  13.6   9.6   0.2
 31  1943  -8.6   1.3  7.1  5.6  13.7  12.6  15.8  15.0  12.8   9.8  -0.8
 32  1944   0.9  -0.6  1.0  7.0   4.7  12.2  17.4  19.8  14.4   5.9   1.7
 33  1945  -4.0   2.0  4.3  7.9  10.4  15.0  15.9  16.6  12.8   9.2   0.1
 34  1946  -2.0  -2.0 -0.6  6.1  11.4  13.1  15.5  16.4  14.6   3.2  -1.0
 35  1947 -11.2  -8.8 -2.3  7.2   8.0  15.8  17.4  20.1  14.8   6.4   3.0
 36  1948  -0.6  -5.6  1.7  7.6   9.4  14.9  12.8  17.3   8.8   3.8   1.0
 37  1949  -0.1  -0.1 -2.9  6.8   9.5  12.9  15.2  16.5  16.0   6.8   3.2
 38  1950  -4.1  -5.1  2.0  5.3   9.9  15.7  17.3  19.5  13.4   1.2   1.7
 39  1951  -4.3  -1.3  0.5  7.5  10.5  15.0  16.0  17.6  14.2   7.2   5.2
 40  1952  -1.0  -0.8  0.0  3.0  12.0  13.7  16.6  17.2   9.5   6.0  -2.3
 41  1953  -2.5  -6.2  3.7  8.2   8.1  13.3  19.2  15.3  13.2   9.1   1.4
 42  1954  -7.4  -8.3  1.2  6.4  11.3  14.1  15.2  14.9   9.9   8.5  -0.1
 43  1955  -5.3  -3.7  0.0  4.8   9.7   9.2  14.0  16.3  13.0   6.7   2.2
 44  1956  -9.6 -13.0  0.0  3.5   8.4  13.7  13.9  12.4  14.2   3.6   1.0
 45  1957  -3.5   2.5  4.5  6.1   8.4  14.9  17.0  14.1  11.5   9.0   1.7
 46  1958  -5.6  -2.4 -0.9  3.5  10.1  14.5  15.0  17.7  14.1   6.8   2.8
 47  1959  -4.5  -4.0  2.8  7.1  13.6  16.4  17.0  17.0  16.1   7.8   0.6
 48  1960  -5.0  -2.2 -1.5  7.2   9.4  12.2  13.7  14.6  10.7   7.4   4.7
 49  1961  -6.3   1.0  4.2  5.5  10.7  14.3  15.0  16.0  14.3   9.4   2.9
 50  1962  -2.5  -1.2 -1.1  6.4   9.0  12.8  12.8  16.5  12.2 -99.9 -99.9

      dec  annual      Station
 0    3.2   -11.0  61700003865
 1   -1.6    -4.2  61700003865
 2   -1.5    -3.3  61700003865
 3   -4.0    -4.6  61700003865
 4   -1.2    -2.4  61700003865
 5   -4.4    -8.4  61700003865
 6    0.4    -3.0  61700003865
 7   -3.6    -6.3  61700003865
 8   -3.8    -3.8  61700003865
 9   -3.2    -3.4  61700003865
 10  -2.2   -10.6  61700003865
 11  -7.2    -7.2  61700003865
 12  -3.2    -6.7  61700003865
 13  -6.2    -6.2  61700003865
 14  -0.7    -5.2  61700003865
 15  -9.2    -9.2  61700003865
 16  -3.5    -4.2  61700003865
 17  -3.0   -12.4  61700003865
 18  -1.7    -1.7  61700003865
 19  -6.6    -6.6  61700003865
 20  -1.1    -2.9  61700003865
 21  -7.2    -7.3  61700003865
 22  -0.4    -2.8  61700003865
 23  -1.4    -5.0  61700003865
 24   0.4    -2.9  61700003865
 25  -3.0    -8.3  61700003865
 26 -12.1   -12.1  61700003865
 27  -4.8    -4.8  61700003865
 28  -4.2   -13.0  61700003865
 29  -3.2   -12.3  61700003865
 30  -1.6   -14.2  61700003865
 31  -4.5    -8.6  61700003865
 32  -3.8    -3.8  61700003865
 33  -4.3    -4.3  61700003865
 34  -7.3    -7.3  61700003865
 35   0.2   -11.2  61700003865
 36  -1.2    -5.6  61700003865
 37   2.7    -2.9  61700003865
 38  -5.0    -5.1  61700003865
 39   2.3    -4.3  61700003865
 40  -3.4    -3.4  61700003865
 41  -0.4    -6.2  61700003865
 42   1.5    -8.3  61700003865
 43  -1.3    -5.3  61700003865
 44  -4.0   -13.0  61700003865
 45  -9.2    -9.2  61700003865
 46  -0.2    -5.6  61700003865
 47  -5.5    -5.5  61700003865
 48  -1.1    -5.0  61700003865
 49  -6.6    -6.6  61700003865
 50 -99.9   -99.9  61700003865  ,
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000  -3.3   3.6   3.8   9.7  14.9  15.6  15.6  21.8  11.0  10.8   5.6
 122  2001  -1.6  -1.2   1.0   5.5   8.5  14.7  14.6  21.0  12.2  12.6   2.7
 123  2002 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 124  2003 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 125  2004 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9

       dec  annual      Station
 0   -99.9   -99.9  LOCID000045
 1   -99.9   -99.9  LOCID000045
 2   -99.9   -99.9  LOCID000045
 3   -99.9   -99.9  LOCID000045
 4   -99.9   -99.9  LOCID000045
 ..    ...     ...          ...
 121  -1.6    -3.3  LOCID000045
 122  -7.6    -7.6  LOCID000045
 123 -99.9   -99.9  LOCID000045
 124 -99.9   -99.9  LOCID000045
 125 -99.9   -99.9  LOCID000045

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 122  2001 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 123  2002 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 124  2003 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 125  2004 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9

       dec  annual      Station
 0   -99.9   -99.9  LOCID000051
 1   -99.9   -99.9  LOCID000051
 2   -99.9   -99.9  LOCID000051
 3   -99.9   -99.9  LOCID000051
 4   -99.9   -99.9  LOCID000051
 ..    ...     ...          ...
 121 -99.9   -99.9  LOCID000051
 122 -99.9   -99.9  LOCID000051
 123 -99.9   -99.9  LOCID000051
 124 -99.9   -99.9  LOCID000051
 125 -99.9   -99.9  LOCID000051

 [126 rows x 15 columns],
      year  jan  feb  mar  apr   may   jun   jul   aug   sep   oct  nov  dec  \
 0    1879 -7.2 -6.2 -0.8  1.8   8.5  17.2  16.0  17.8  13.8   7.8 -5.8 -8.5
 1    1880 -5.4 -0.4  4.0  5.0  11.4  14.0  19.2  17.2  15.4   3.1  1.8  0.7
 2    1881 -9.2 -5.0 -2.5  4.8   9.2   8.2  16.0  17.4  12.4   2.4 -0.2 -1.4
 3    1882 -0.5 -0.4  5.0  6.8   7.6  12.4  16.8  14.0  14.4   3.8 -0.2 -4.5
 4    1883 -2.9  0.2 -2.0  5.8   9.7  15.0  17.0  16.6  13.2   8.8  2.2 -3.5
 ..    ...  ...  ...  ...  ...   ...   ...   ...   ...   ...   ...  ...  ...
 121  2000 -2.3  1.0  4.1  8.0  12.6  15.2  15.7  18.3  12.0  10.7  4.2 -1.7
 122  2001 -2.1 -3.8  0.1  3.9   8.0  13.2  14.3  17.7  11.3   9.4  2.3 -4.1
 123  2002 -2.7  1.8  2.3  5.4  14.9  16.4  16.8  18.3  11.6   4.9  1.8 -7.0
 124  2003 -6.4 -2.6  2.4  2.6  14.8  19.1  17.9  18.8  14.8   4.4  3.8  0.3
 125  2004 -7.6 -0.4  1.2  9.0  11.1  17.5  17.3  17.5  13.7   9.7  1.6 -1.2

      annual      Station
 0      -8.5  LOCID000050
 1      -5.4  LOCID000050
 2      -9.2  LOCID000050
 3      -4.5  LOCID000050
 4      -3.5  LOCID000050
 ..      ...          ...
 121    -2.3  LOCID000050
 122    -4.1  LOCID000050
 123    -7.0  LOCID000050
 124    -6.4  LOCID000050
 125    -7.6  LOCID000050

 [126 rows x 15 columns],
      year   jan   feb   mar   apr   may   jun   jul   aug   sep   oct   nov  \
 0    1879 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 1    1880 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 2    1881 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 3    1882 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 4    1883 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 ..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
 121  2000 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 122  2001 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 123  2002 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 124  2003 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9
 125  2004 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9 -99.9

       dec  annual      Station
 0   -99.9   -99.9  LOCID000044
 1   -99.9   -99.9  LOCID000044
 2   -99.9   -99.9  LOCID000044
 3   -99.9   -99.9  LOCID000044
 4   -99.9   -99.9  LOCID000044
 ..    ...     ...          ...
 121 -99.9   -99.9  LOCID000044
 122 -99.9   -99.9  LOCID000044
 123 -99.9   -99.9  LOCID000044
 124 -99.9   -99.9  LOCID000044
 125 -99.9   -99.9  LOCID000044

 [126 rows x 15 columns],
     year   jan  feb  mar  apr   may   jun   jul   aug   sep  oct  nov   dec  \
 0   1901 -10.7 -6.1  0.9  7.1  12.9  14.6  19.9  16.1  13.3  9.3  0.9  -2.9
 1   1902   0.7 -2.7 -0.7  6.6   7.7  14.9  16.4  15.0  11.2  3.8 -4.2  -8.5
 2   1903  -5.4 -0.2  2.9  4.2  11.5  16.4  17.9  17.0  11.0  6.8  1.3  -2.5
 3   1904  -4.5 -2.6 -0.5  8.9  11.9  15.4  19.1  19.1  10.1  5.8  1.2   1.0
 4   1905  -8.1 -0.1  0.7  3.9  11.7  16.8  17.7  17.1  13.9  4.4  1.3  -2.4
 ..   ...   ...  ...  ...  ...   ...   ...   ...   ...   ...  ...  ...   ...
 94  1995  -5.2  1.8  1.2  6.8  10.2  11.4  18.6  14.4  11.9  7.9  0.0  -9.8
 95  1996  -8.8 -8.6 -1.4  3.6   7.1  14.0  15.2  20.3  10.3  9.3  1.0 -10.8
 96  1997 -11.2  0.6  1.9  8.1  11.7  17.1  17.4  19.3  15.2  5.7  0.4  -7.8
 97  1998  -4.0 -3.1  2.4  7.0  13.4  16.5  15.4  15.2  13.4  5.0 -4.8  -5.5
 98  1999  -3.0 -0.6  3.2  6.0  11.1  15.3  18.3  18.1  17.0  7.9  0.6   0.2

     annual      Station
 0    -10.7  61700003319
 1     -8.5  61700003319
 2     -5.4  61700003319
 3     -4.5  61700003319
 4     -8.1  61700003319
 ..     ...          ...
 94    -9.8  61700003319
 95   -10.8  61700003319
 96   -11.2  61700003319
 97    -5.5  61700003319
 98    -3.0  61700003319

 [99 rows x 15 columns],

In [2]:
for i, df in enumerate(dataframes, start=1):
    print(f"Shape of csv{i}:", df.shape)

Shape of csv1: (99, 15)
Shape of csv2: (126, 15)
Shape of csv3: (126, 15)
Shape of csv4: (135, 15)
Shape of csv5: (126, 15)
Shape of csv6: (135, 15)
Shape of csv7: (51, 15)
Shape of csv8: (126, 15)
Shape of csv9: (126, 15)
Shape of csv10: (126, 15)
Shape of csv11: (126, 15)
Shape of csv12: (99, 15)
Shape of csv13: (126, 15)
Shape of csv14: (126, 15)
Shape of csv15: (129, 15)
Shape of csv16: (126, 15)
Shape of csv17: (83, 15)
Shape of csv18: (99, 15)
Shape of csv19: (99, 15)
Shape of csv20: (93, 15)
Shape of csv21: (99, 15)
Shape of csv22: (91, 15)
Shape of csv23: (129, 15)
Shape of csv24: (126, 15)
Shape of csv25: (99, 15)
Shape of csv26: (99, 15)
Shape of csv27: (90, 15)
Shape of csv28: (99, 15)
Shape of csv29: (99, 15)
Shape of csv30: (99, 15)
Shape of csv31: (126, 15)
Shape of csv32: (126, 15)
Shape of csv33: (99, 15)
Shape of csv34: (121, 15)
Shape of csv35: (126, 15)
Shape of csv36: (126, 15)
Shape of csv37: (99, 15)
Shape of csv38: (109, 15)

In [3]:
print(type(dataframes))

<class 'list'>

In [4]:
import pandas as pd

def merge_csv_files(file_paths):
    dfs = []

    for file_path in file_paths:
        df = pd.read_csv(file_path)
        dfs.append(df)

    
    merged_df_TXn = pd.concat(dfs, ignore_index=True)

    return merged_df_TXn

merged_df_TXn = pd.concat(dataframes, ignore_index=True)
merged_df_TXn

,year,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,annual,Station
0,1901,-10.9,-5.6,-0.1,7.8,12.9,14.9,17.0,15.1,13.1,4.0,-1.6,-1.7,-10.9,61700004063
1,1902,-0.5,-1.2,4.6,10.4,9.3,14.3,16.8,15.3,13.0,4.4,-2.0,-10.6,-10.6,61700004063
2,1903,-5.6,2.3,5.0,6.0,13.0,16.7,16.0,16.0,9.3,10.3,1.3,-5.1,-5.6,61700004063
3,1904,-4.5,-2.1,0.6,9.0,10.5,18.0,20.4,13.0,10.3,7.4,-0.1,-3.0,-4.5,61700004063
4,1905,-9.5,-0.1,4.2,6.0,10.8,18.3,18.0,16.5,12.7,3.0,1.4,-2.8,-9.5,61700004063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4239,1995,-6.1,2.5,1.3,7.1,10.3,14.0,18.0,17.5,10.1,10.2,1.1,-8.9,-8.9,61700010147
4240,1996,-7.2,-8.3,0.0,3.4,6.5,13.0,14.6,16.9,14.6,10.2,0.6,-8.6,-8.6,61700010147
4241,1997,-10.8,2.7,2.5,7.6,9.2,14.8,18.2,19.6,13.8,6.4,0.8,-5.5,-10.8,61700010147
4242,1998,-0.4,-3.1,4.4,6.2,11.9,15.2,15.3,14.7,13.6,8.1,-3.8,-4.0,-4.0,61700010147
4243,1999,-0.7,-2.4,3.7,6.0,11.0,14.9,17.2,17.4,18.3,7.7,1.5,0.6,-2.4,61700010147

In [5]:
merged_df_TXn.head(30)

,year,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,annual,Station
0,1901,-10.9,-5.6,-0.1,7.8,12.9,14.9,17.0,15.1,13.1,4.0,-1.6,-1.7,-10.9,61700004063
1,1902,-0.5,-1.2,4.6,10.4,9.3,14.3,16.8,15.3,13.0,4.4,-2.0,-10.6,-10.6,61700004063
2,1903,-5.6,2.3,5.0,6.0,13.0,16.7,16.0,16.0,9.3,10.3,1.3,-5.1,-5.6,61700004063
3,1904,-4.5,-2.1,0.6,9.0,10.5,18.0,20.4,13.0,10.3,7.4,-0.1,-3.0,-4.5,61700004063
4,1905,-9.5,-0.1,4.2,6.0,10.8,18.3,18.0,16.5,12.7,3.0,1.4,-2.8,-9.5,61700004063
5,1906,-3.4,-0.1,-0.1,10.0,12.3,13.7,12.7,17.4,10.6,4.2,1.8,-6.2,-6.2,61700004063
6,1907,-7.8,-2.6,1.2,8.4,6.2,14.8,13.7,11.4,14.0,10.0,0.3,-2.9,-7.8,61700004063
7,1908,-5.3,-1.0,2.3,4.4,10.2,16.2,16.6,13.8,14.1,1.2,-0.9,-9.5,-9.5,61700004063
8,1909,-6.0,-3.8,-0.9,5.5,9.7,13.0,13.2,14.9,14.2,8.0,-0.9,-2.0,-6.0,61700004063
9,1910,0.5,0.9,4.0,8.7,9.2,15.9,14.2,18.3,9.1,8.6,-1.4,-3.0,-3.0,61700004063
10,1911,-6.4,-2.9,4.7,1.0,12.8,16.7,19.4,21.8,13.5,8.6,3.7,2.3,-6.4,61700004063
11,1912,-7.3,-8.0,8.2,6.0,11.0,16.2,16.8,14.7,9.6,4.6,-0.1,-3.0,-8.0,61700004063
12,1913,-5.5,0.0,3.9,3.7,7.8,13.7,15.5,14.5,15.6,5.7,3.7,-2.4,-5.5,61700004063
13,1914,-5.0,1.6,2.7,10.2,9.7,12.1,15.6,19.1,10.8,6.2,0.0,-0.1,-5.0,61700004063
14,1915,-4.6,-1.0,-2.0,6.3,12.5,20.5,15.6,15.3,10.8,4.1,-5.8,-1.9,-5.8,61700004063
15,1916,1.8,-2.6,2.7,7.1,13.4,12.3,18.0,15.2,12.6,4.1,-1.0,-1.4,-2.6,61700004063
16,1917,-7.0,-8.4,-0.1,5.4,15.5,19.0,18.0,16.2,13.9,3.0,3.4,-6.3,-8.4,61700004063
17,1918,-3.4,-1.0,3.4,4.8,10.6,14.5,13.5,17.3,14.0,7.0,0.5,-0.5,-3.4,61700004063
18,1919,-3.9,-4.4,1.8,3.7,8.3,13.5,15.2,15.7,9.8,0.9,-0.4,-4.2,-4.4,61700004063
19,1920,-0.3,4.0,4.4,9.9,11.0,13.3,17.2,12.4,14.9,1.9,-1.0,-6.7,-6.7,61700004063
20,1921,-1.8,0.1,2.3,7.4,7.2,14.0,15.5,17.0,15.3,6.5,-4.5,-8.0,-8.0,61700004063
21,1922,-5.6,-9.1,-1.6,5.2,10.8,15.9,11.5,15.6,9.9,1.9,-0.9,-4.2,-9.1,61700004063
22,1923,-0.6,-2.8,3.2,6.2,11.4,11.6,17.3,16.9,11.8,9.4,-0.8,-13.8,-13.8,61700004063
23,1924,-7.6,-3.8,2.4,4.6,10.1,14.7,15.6,13.2,14.3,8.2,-1.9,-2.7,-7.6,61700004063
24,1925,-1.3,1.1,-0.7,7.9,8.1,14.2,16.9,16.3,10.8,4.7,-3.1,-12.1,-12.1,61700004063
25,1926,-6.0,4.1,2.1,10.6,9.1,13.2,15.7,15.0,14.1,3.9,1.1,-3.4,-6.0,61700004063
26,1927,-1.0,-2.9,3.0,7.3,8.1,14.1,15.7,14.4,12.0,8.4,0.4,-8.0,-8.0,61700004063
27,1928,-4.3,-0.4,-0.7,4.2,5.3,13.0,19.2,17.5,12.1,6.2,1.4,-6.5,-6.5,61700004063
28,1929,-8.5,-16.4,-1.6,-0.7,10.3,13.3,16.0,15.4,14.2,7.3,3.5,-0.4,-16.4,61700004063
29,1930,-0.7,0.8,2.8,5.3,10.4,19.8,15.5,13.3,14.1,8.1,4.3,-3.2,-3.2,61700004063

In [6]:
merged_df_TXn.to_csv('merged_df_TXn.csv', index=False)